### ISSUE TITLE
List-Reply broken

### ISSUE THREAD

**Issue by patrickbenkoetter** [neomutt/neomutt#2320] opened 2020-05-07 17:43 UTC
## Expected Behaviour

Hitting CTRL-L should trigger a list reply.

## Actual Behaviour

Nothing happens when I type CTRL-L

Instead NeoMutt issues a "no mailing list detected" notification

## Steps to Reproduce

Open a message from neomutt-users@neomutt.org and type CTRL-L.

## How often does this happen?

- Always

## When did it start to happen?

With the recent release.

## NeoMutt Version

NeoMutt 20200501

```
[p@p ~]$ neomutt -v
NeoMutt 20200501
Copyright (C) 1996-2016 Michael R. Elkins und andere.
NeoMutt übernimmt KEINERLEI GEWÄHRLEISTUNG. Starten Sie 'neomutt -vv', um
weitere Details darüber zu erfahren. NeoMutt ist freie Software.
Sie können es unter bestimmten Bedingungen weitergeben; starten Sie
'neomutt -vv' für weitere Details.

System: Linux 5.6.10-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.13.1
GnuTLS: 3.6.13
libnotmuch: 5.2.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Standard Einstellungen:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Einstellungen bei der Kompilierung:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +lz4 +meta -mixmaster +nls +notmuch -openssl +pgp +regex 
  +sasl +smime +sqlite +start_color +sun_attachment +typeahead +zlib +zstd 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info
* Operating System and its version
ARCHLINUX but also reported on list to apply to Apple homebrew/linuxbrew.

**Comment by jindraj** [comment] 2020-05-07 18:17
>Instead NeoMutt issues a "no mailing list detected" notification

According to following error it sounds like the address of the mailing list isn't listed as a list or subscribed.

See: [mailing-lists](https://neomutt.org/guide/configuration.html#13-%C2%A0mailing-lists) in Guide.

Use either `list` or `subscribe` command. Then it should work as expected.
example
```
lists -group neomutt '^neomutt-users@neomutt.org$'
lists -group neomutt '^neomutt-devel@neomutt.org$'
```
You can also let neomutt automatically subscribe to lists based on **List-Post header**
```
set auto_subscribe = yes
```

**Comment by patrickbenkoetter** [comment] 2020-05-07 18:30
Confirmed.

**Comment by nobrowser** [comment] 2020-05-08 03:24
But "subscribing" the list in this sense (a misleading term) has never been necessary in mutt or netmutt up until now. That is, you could find a completely isolated message, even outside of any folder, and provided it had a List-Post header, you could directly reply to that list. So this *is* a regression.

**Comment by nobrowser** [comment] 2020-05-08 03:48
And `set auto_subscribe=yes `doesn't work: same error message.

Opening new issue.

**Comment by gahr** [comment] 2020-05-08 06:34
This is a regression.

The problem is an email is tagged as being in a list by first checking whether the content of List-Post is a mailto URI. This check is done skipping the opening `<` and sending all the rest **including the closing `>`** to `url_check_scheme`. Recent changes to URL parsing code no longer take URIs like `mailto:crypto-gram@schneier.com>` as valid, because of the closing `>`.

**Closed** 2020-05-08 09:51 UTC
Labels: bug:confirmed
