### ISSUE TITLE
How to use nospam ?

### ISSUE THREAD

**Issue by amartos** [neomutt/neomutt#1786] opened 2019-07-23 13:34 UTC
Hello everyone.

I tried to use the spam/nospam commands, and although `spam` works as expected,
`nospam` does not exclude correct patterns. 

As I have not found any issue or anyone on the net talking about that, maybe I 
did get it wrong ? What am I missing here ? 

As I'm not sure of what I'm doing wrong, I used the bug template to give full
infos, sorry if it's too much.

## Expected Behaviour

As described in the [reference guide](https://neomutt.org/guide/configuration.html#23-%C2%A0spam-detection):

```
spam "X-Spam-Status: Yes" "!"
nospam "From:.*address@provider.com.*"
```

should flag all mails with "X-Spam-Status: Yes" in header as spam, except for
mails from address[at]provider.com.

## Actual Behaviour

`spam` does flag mails as spam, as expected, but `nospam` does not exclude
mails from address[at]provider.com. Inverting the commands like this

```
nospam "X-Spam-Status: Yes"
spam "From:.*address@provider.com.*" "!"
```

flags all address[at]provider.com mails as spam but does not exclude mails with 
"X-Spam-Status: Yes" in headers.

However, 
```
spam "X-Spam-Status: Yes" "!"
nospam "X-Spam-Status: Yes"
# or nospam *
```
does cancel spam flagging, as expected.

## Steps to Reproduce

Open neomutt with these config (anonymized) files: [neomutt_config.tar.gz](https://github.com/neomutt/neomutt/files/3422187/neomutt_config.tar.gz)

## How often does this happen?

Always.

I tried with multiple mail addresses, with `spam_separator` set/unset/not in
config, and I tried changing the order of the spam/nospam commands. 

I also tried other patterns (even copy/paste from the mail header itself),
but only either the same pattern as in `spam` or `*` work.

## When did it start to happen?

When I started using the spam/nospam commands.

## NeoMutt Version

From Debian 10 repos.

```
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins et autres.
NeoMutt ne fournit ABSOLUMENT AUCUNE GARANTIE ; pour les détails tapez 'neomutt -vv'.
NeoMutt est un logiciel libre, et vous êtes libre de le redistribuer
sous certaines conditions ; tapez 'neomutt -vv' pour les détails.

System: Linux 4.19.0-5-amd64 (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20180714)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 7.3.0-25' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Debian 7.3.0-25) 

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/lib --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-oDMtzm/neomutt-20180716+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3  -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Options de compilation :
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  +gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  +mixmaster +nls +notmuch -openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Debian 10
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
No
* Is your email local (maildir) or remote (IMAP)?
local + offlineimap + notmuch

## Debug logs

Here are the relevant sections of debug logs level 5 for one mail that 
matches both "X-Spam-Status: Yes" and "From:.\*address@provider.com.\*".

With `spam "X-Spam-Status: Yes" "!"` and `nospam "From:.*address@provider.com.*"`:
```
[2019-07-23 12:56:37] NeoMutt-20180716 debugging at level 5
[...]
[2019-07-23 12:56:41]<2> append_message() nm: appending message, i=56, id=XXX@mail.gmail.com, path=/home/USER/mails/archive/cur/1563818549_1.12824.ideapad,U=153,FMD5=888d0ee361af3603736f32131e7b20a2:2,S
[2019-07-23 12:56:41]<2> parse_parameters() 'charset=utf-8'
[2019-07-23 12:56:41]<2> parse_parameters() parse_parameter: 'charset' = `utf-8'
[2019-07-23 12:56:41]<5> mutt_replacelist_match() X-Spam-Status: Yes, score=6.7 required=4.0 tests=DKIM_SIGNED,DKIM_VALID, DKIM_VALID_AU,DKIM_VALID_EF,FREEMAIL_FROM,FROM_EXCESS_BASE64, FSL_BULK_SIG,HTML_MESSAGE,RAZOR2_CF_RANGE_51_100,RAZOR2_CHECK,SPF_PASS autolearn=no autolearn_force=no version=3.4.2 matches X-Spam-Status: Yes
[2019-07-23 12:56:41]<5> mutt_replacelist_match() 0 subs
[2019-07-23 12:56:41]<5> mutt_replacelist_match() "!"
[2019-07-23 12:56:41]<5> mutt_rfc822_read_header() spam = !
[2019-07-23 12:56:41]<2> init_header() nm: initialize header data: [hdr=0x559c1753c970, data=0x559c17494be0] (XXX@mail.gmail.com)
[2019-07-23 12:56:41]<2> update_message_path() nm: path update requested path=/home/USER/mails/archive/cur/1563818549_1.12824.ideapad,U=153,FMD5=888d0ee361af3603736f32131e7b20a2:2,S, (XXX@mail.gmail.com)
[2019-07-23 12:56:41]<2> update_message_path() nm: folder='/home/USER/mails/archive', file='cur/1563818549_1.12824.ideapad,U=153,FMD5=888d0ee361af3603736f32131e7b20a2:2,S'
[2019-07-23 12:56:41]<2> update_header_tags() nm: tags update requested (XXX@mail.gmail.com)
[2019-07-23 12:56:41]<2> update_header_tags() nm: new tags: '(null)'
[2019-07-23 12:56:41]<2> update_header_tags() nm: new tag transforms: '(null)'
```

With `nospam "X-Spam-Status: Yes"` and `spam "From:.*address@provider.com.*" "!"`:
```
[2019-07-23 12:58:25] NeoMutt-20180716 debugging at level 5
[...]
[2019-07-23 12:58:29]<2> append_message() nm: appending message, i=56, id=XXX@mail.gmail.com, path=/home/USER/mails/archive/cur/1563818549_1.12824.ideapad,U=153,FMD5=888d0ee361af3603736f32131e7b20a2:2,S
[2019-07-23 12:58:29]<2> parse_parameters() 'charset=utf-8'
[2019-07-23 12:58:29]<2> parse_parameters() parse_parameter: 'charset' = `utf-8'
[2019-07-23 12:58:29]<5> mutt_replacelist_match() From: =?utf-8?b?CHARS?= <address@provider.com> matches From:.*address@provider.com.*
[2019-07-23 12:58:29]<5> mutt_replacelist_match() 0 subs
[2019-07-23 12:58:29]<5> mutt_replacelist_match() "!"
[2019-07-23 12:58:29]<5> mutt_rfc822_read_header() spam = !
[2019-07-23 12:58:29]<2> init_header() nm: initialize header data: [hdr=0x56508c457920, data=0x56508c580ef0] (XXX@mail.gmail.com)
[2019-07-23 12:58:29]<2> update_message_path() nm: path update requested path=/home/USER/mails/archive/cur/1563818549_1.12824.ideapad,U=153,FMD5=888d0ee361af3603736f32131e7b20a2:2,S, (XXX@mail.gmail.com)
[2019-07-23 12:58:29]<2> update_message_path() nm: folder='/home/USER/mails/archive', file='cur/1563818549_1.12824.ideapad,U=153,FMD5=888d0ee361af3603736f32131e7b20a2:2,S'
[2019-07-23 12:58:29]<2> update_header_tags() nm: tags update requested (XXX@mail.gmail.com)
[2019-07-23 12:58:29]<2> update_header_tags() nm: new tags: '(null)'
[2019-07-23 12:58:29]<2> update_header_tags() nm: new tag transforms: '(null)'
```

**Comment by gahr** [comment] 2019-07-23 14:07
From my reading through the [code](https://github.com/neomutt/neomutt/blob/5859dd277b52b189e028061e7e2835060153537f/email/parse.c#L1080-L1082) and the [docs](https://neomutt.org/guide/configuration.html#23-%C2%A0spam-detection) , I think the way I understand it is that `nospam` should allow you to unmark a message previously marked as spam by applying a finer-grained regex to the **same header** that caused the message to be marked as spam in the first place. Yes, it does sound convoluted.

**Comment by amartos** [comment] 2019-07-23 14:23
I see. Indeed it does work if i try
```
spam "X-Spam-Status: Yes" "!"
nospam "X-Spam-Status: Yes, score=6.7"
```
Being able to use multiple patterns would be handful IMO.
Anyway, thanks a lot for your answer.

**Comment by gahr** [comment] 2019-07-23 14:31
The problem is that `unspam` is not meant to mark a whole email as not spam, but to undo the action of a particular match: you undo a particular spam tag, but you could have many defined:

```
spam "X-Spam-Status: Yes" "!"
spam "From:.*boss.*" "OH NOES"
unspam "From:.*boss@neomutt.org"
```

So an email with the `X-Spam-Status: Yes` header coming from `boss@neomutt.org` would still get the `!` spam flag set, but would not get the `OH NOES` flag set because of the `unspam` command.

HTH

**Comment by amartos** [comment] 2019-07-23 14:52
Yes, I understand. Using `X-Spam-Status: Yes` as a pattern thus implies to properly teach the external filter how to recognize spams.

Thanks a lot. :)

**Closed** 2019-07-23 17:26 UTC
