### ISSUE TITLE
Viewing a .tar.gz attachment a second time fails (regression)

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#1699] opened 2019-05-04 07:47 UTC
## Expected Behaviour

If I open an attached tar.gz for a second time, it should open in the same way as when opened the first time.

## Actual Behaviour

Upon opening it a second time, file-roller opens but not with the correct contents.

## Steps to Reproduce

If I press "v" to get to the attachments menu, and then press "j" to go down to select the attached tar.gz, and then press `<enter>` to open it, it works fine the first time (i.e., it opens file-roller which displays the correct contents). However, if I quit file-roller, which takes me back to mutt, and press `<enter>` again, file-roller opens but not with the correct contents.

## How often does this happen?

- Always (for the two tar.gz files I tested)

## When did it start to happen?

Bisect leads to 39a03d5e.

## NeoMutt Version

```
$ mutt -v
NeoMutt 20180716-1739-896193
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.0.0-13-generic (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20181013)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-6ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1) 

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss +hcache -homespool +idn +inotify -locales_hack -lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
$ 
```

**Comment by scottkosty** [comment] 2019-05-18 00:26
@0x747972 Can you reproduce?

**Comment by flatcap** [comment] 2019-05-21 12:24
Sorry for the slow reply.
I can't reproduce this.

I sent myself two `.tar.gz` attachments and set my mailcap to `application/gzip; /usr/bin/file-roller %s;`

I then viewed the each attachment repeatedly and then alternating between the two.
The file-roller is always displayed with the right file.

I also checked `<view-attachments>` from both the index and the pager.

**Comment by scottkosty** [comment] 2019-05-21 19:56
@flatcap thanks for trying to reproduce! If @0x747972 can't reproduce, I'll try to figure out how to add more details.

**Comment by 0x747972** [comment] 2019-05-22 16:40
Hey Scott,

I've neither been able to reproduce this.
Could you please show us your  .mailcap and probably .muttrc?
What do you mean by "wrong content"?

**Comment by scottkosty** [comment] 2019-05-22 18:09
@0x747972 and @flatcap thank you both for trying to reproduce. I'll try to look into this further and provide more information. Since I know the commit that changed behavior for me, I should be able to figure out how to add debug code and narrow down what changed for me. Thanks for the tips @0x747972 , I'll try to narrow down a minimal example .muttrc and .mailcap.

**Comment by scottkosty** [comment] 2019-06-09 07:57
@0x747972 @flatcap 
The mailcap entry responsible for the viewing is in `/etc/mailcap` and is the following entry:

```
application/gzip; file-roller %s; test=test -n "$DISPLAY"
```

Here is a minimal .muttrc (I can reproduce both with using mutt on a local maildir and remotely with IMAP):

```
set realname = 'Scott Kostyshak'
set imap_user = 'scott.kostyshak@gmail.com'
set imap_pass = <hidden>

set folder = "~/.mail"

set smtp_url = "smtp://scott.kostyshak@smtp.gmail.com:587/"
set smtp_pass = <hidden>

set spoolfile = +INBOX
```

The following relevant line is in the debug output:
```
[2019-06-09 02:06:31]<3> mutt_buffer_mktemp_full() muttlib.c:113: mutt_mktemp returns "/tmp/testing.tar-hname-1000-28916-1681692777846930886.gz"
```

It seems that on the second opening of the attachment, mutt sees that `/tmp/testing.tar.gz` exists and does not want to overwrite it so it uses a new temporary name but as shown above, it fails to preserve the two-part extension. The extension of the second name is "gz", where it should be "tar.gz". Thus, file-roller thinks it is opening a "gz" file, not a "tar.gz" file, and that is why it shows up incorrectly for me. From what I understand, 39a03d5 changed things by not deleting the file in-between the two openings, and thus it made the renaming necessary (now, it appears the deletions happen upon quitting mutt).

The new temporary name is not surprising. The suffix is calculated using an understandably simple way (see https://github.com/neomutt/neomutt/blob/master/muttlib.c#L107):

```
    char *suffix = strrchr(prefix->data, '.');
```
I specify "understandably" above since there's no straightforward way I know of to perfectly handle multi-part extensions. The only solution I can think of to extract the extension would be to use a hardcoded list of multipart extensions.

I think 39a03d5 just happened to trigger this existing non-ideal extension extraction. Fun coincidence of the day: 39a03d5 was motivated by #1298 which was annoying because Firefox only worked on the *second* try; and the behavior in this issue is about an annoyance from viewing a tar.gz a *second* try :)

I still don't understand why we see different behavior. Is the tar.gz deleted after you close file-roller the first time? What is the file name when you open file-roller the second time? Perhaps your file-roller version is just smarter than mine and knows that the .gz file is really a .tar.gz file? Perhaps the mutt timeout hook (950a4655) is somehow triggered for you but on my system it is not (or just really long)?

```
$ file-roller --version
file-roller 3.32.1, Copyright © 2001-2012 Free Software Foundation, Inc.
```

Perhaps figuring out the answer to why we see different behavior will guide us to the best approach for a fix. I throw out a few ideas:

1. Improve the extension extraction (e.g., with a hardcoded list or rely on a third-party function).
2. Add randomness to the *beginning* of the filename (instead of trying to locate the middle). This will not change the extension. However, programs usually display the filename in the titlebar, and also if resaving it might look less-than-ideal.
3. If the file exists, save to a temporary *directory*. This way, the basename can be preserved.

**Comment by flatcap** [comment] 2019-06-23 11:30
Thanks for the debugging, @scottkosty.

Now I understand (and I can repeat it).
You've found two problems.

> It seems that on the second opening of the attachment, mutt sees that /tmp/testing.tar.gz exists and does not want to overwrite it

Yes.  The email doesn't keep track of the filename it uses for the attachment.
When we re-open the attachment, the file already exists so we try a different name.

One of your ideas might be a good long-term solution:
Create a tmp directory per email for attachments.

When we first open an attachment, we create a dir for the tmp file.
We remember this name, so we can reuse the file later.

Any duplicate names will still need to be made unique.

Currently, the tmp files are cleaned up after `$timeout`.
An alternative might be to keep them for the lifetime of the email.

> it fails to preserve the two-part extension

Well spotted.

> ... hardcoded list of multipart extensions ...

Argh! :-)

> The suffix is calculated [splitting at the last dot]

I suggest a quick and simple fix for this.
Splitting the filename at the first dot.

```diff
-    char *suffix = strrchr(prefix->data, '.');
+    char *suffix = strchr(prefix->data, '.');
```

| Name              | Start    | Suffix       | Result     |
| :---------------- | :------- | :----------- | :--------- |
| `file.tar`        | `file`   | `tar`        | Good       |
| `file.tar.gz`     | `file`   | `tar.gz`     | Good       |
| `.neomuttrc`      | [none]   | `.neomuttrc` | Reasonable |
| `hello.world.txt` | `hello`  | `world.txt`  | Acceptable |

> Add randomness to the beginning of the filename. This will not change the extension.
> However, programs usually display the filename in the titlebar, and also if resaving it might look less-than-ideal.

Currently, we insert a lot of text in order to be statistically unique, e.g. `laptop-1002-7827-14943018067700764844`
Using your separate directory idea, we could insert short numeric strings.

> Fun coincidence of the day: 39a03d5 was motivated by #1298 which was annoying because Firefox only worked on the second try; and the behavior in this issue is about an annoyance from viewing a tar.gz a second try :)

:-)

> I still don't understand why we see different behavior.

I think I do, now.
I wasn't paying enough attention to _what_ the file-roller was displaying.
(I have the same version as you)

| File type | File name | File-Roller displays  |
| :-------- | :-------- | :-------------------- |
| tar       | b1.tar    | contents of tar       |
| tar       | b2        | fails to open         |
| tar,gzip  | b3.tar.gz | contents of tar       |
| tar,gzip  | b4.tgz    | contents of tar       |
| tar,gzip  | b5.tar    | contents of tar       |
| tar,gzip  | b6.gz     | decompressed tar file |
| tar,gzip  | b7        | decompressed tar file |

---

Please can you give the one-liner fix a try.  Hopefully, it'll solve your problem.

Making the attachment file handling smarter, could be a lot of work, so I'll need a volunteer.

Thanks.

**Comment by scottkosty** [comment] 2019-06-24 01:31
> `hello.world.txt`	`hello`	`world.txt`	Acceptable

Ah nice. I didn't consider this possibility but this should indeed be correctly opened. I think it's a nice quick fix.

> Please can you give the one-liner fix a try. Hopefully, it'll solve your problem.

Yep works well! Thanks for the fix.

> so I'll need a volunteer

Not me :)

**Closed** 2019-07-15 10:23 UTC
Labels: has:bisect, type:bug
