### ISSUE TITLE
Empty folders since the last update of neomut (2019-10-25) on my arch linux

### ISSUE THREAD

**Issue by AndreasAZiegler** [neomutt/neomutt#1903] opened 2019-10-29 19:33 UTC
After I finding myself in front of "empty" folders when I change from the inbox into another folder, I saw on the change log, that ```folder_format``` has a new default value. I assume that this is the problem I'm facing. What was the previous default value, how can I change it and or should I solve the problem in another way (as the previous way how folders were handled is deprecated?)?

**Comment by Krakonos** [comment] 2019-10-31 12:24
Hi! This might be related to issue #1887 . folder_format is the display format, not the physical format, so I guess it is not related.

#1887 TL;DR: In my case, it was caused by a mailbox entry in 'mailboxes' that does not exist.  You might want to limit mailboxes to inbox and one known entry to see if it helps.

**Comment by AndreasAZiegler** [comment] 2019-10-31 12:46
Yes, it looks similar. When I start ```neomutt -f /path/to/folder``` I see the content of the specific folder. However, I run ```grep -rn 'maillboxes' .``` and couldn't find any 'mailboxes' entry (only commented-out ones).

**Comment by Krakonos** [comment] 2019-10-31 13:49
Are you using local mailboxes or IMAP? Because I use IMAP only.

**Comment by flatcap** [comment] 2019-10-31 13:50
The browser has two views; you can switch between them with <kbd>Tab</kbd>.

One view shows the list of Mailboxes that you've specified with the `mailboxes` command.
(the also show up in the sidebar).
The other view shows all the Mailboxes that NeoMutt knows about (IMAP), or a directory view (Maildir).

**Comment by flatcap** [comment] 2019-10-31 13:50
The `folder_format` changed from/to:
- `%2C %t %N %F %2l %-8.8u %-8.8g %8s %d %f`
- `%2C %t %N %F %2l %-8.8u %-8.8g %8s %d %i`

The new field `%i` (description) defaults to `%f` (filename) (the old behaviour).

**Comment by AndreasAZiegler** [comment] 2019-10-31 17:24
@Krakonos I'm using local mailboxes (which are synced with mbsync/isync).

**Comment by bunwayenterprises** [comment] 2019-11-02 10:57
I'm experiencing the same issue with no maildir folders displaying when using a custom ```folder_format``` of ```%2C %t %N %f```.

Probably not related, but I note that manually changing ```%f``` to ```%i``` causes a syntax error in vim's syntax highlighting.

In the meantime i've downgraded to the prior version of ```neomutt-20180716-8-x86_64```.

Happy to provide any information needed to help troubleshoot.

**Comment by flatcap** [comment] 2019-11-02 14:05
@bunwayenterprises 
> changing `%f` to `%i` causes a syntax error in vim's syntax highlighting.

The [neomutt.vim](https://github.com/neomutt/neomutt.vim) repo has the latest syntax files.
I've also [submitted them](https://github.com/vim/vim/pull/5163) to vim (neovim automatically pick up their changes).

**Comment by AndreasAZiegler** [comment] 2019-11-08 05:21
I now also downgraded to ```neomutt-20180716-8-x86_64``` and waiting hopefully for a fix. I'm also happily willing to provide further information for troubleshooting.

**Comment by AndreasAZiegler** [comment] 2019-11-15 06:58
Solved with 20191111 release. Thanks for your efforts.

**Comment by AndreasAZiegler** [comment] 2019-12-04 16:14
Again present in NeoMutt 20191129.

**Comment by bunwayenterprises** [comment] 2019-12-08 13:09
Also seeing this regression in 20191207-1.

**Comment by amerlyq** [comment] 2019-12-09 17:08
Is this issue related to disappearing of entries from a "directory view" ?
On ArchLinux neomutt 20191129 and neomutt-git 20191207 both don't show `INBOX` folder in directory view at all, only in virtual mailboxes view (on `<Tab>`).
And older master branch neomutt-git `20191111.r9` resulted in disappearing of a folder under cursor each time you open it -- literally making them one-timers. Does this gradual disappearance provide some hint?

**Comment by ehrlichja** [comment] 2021-01-07 03:59
I'm having this problem too. When I hit `c` and browse to `Folders/xyz`, that folder is just empty and there is no way to select.

**Comment by roccoblues** [comment] 2023-12-21 08:12
Hi, I'm trying to cleanup some older issues here. Can you still reproduce this behavior with the latest version? Thanks!

**Comment by Krakonos** [comment] 2023-12-21 17:02
I can't, my issue had a different cause though.

**Comment by amerlyq** [comment] 2023-12-21 22:12
I didn't use neomutt in last 3 years, no feedback from me.

Personally I would say it's ok to close the issue with appropriate comment, and wait until somebody unsatisfied will reopen it or create a new with more new/relevant details.

**Closed** 2023-12-28 09:33 UTC
