### ISSUE TITLE
20200814 reports an unclear error about my muttrc on startup

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#2594] opened 2020-08-17 10:11 UTC
## Expected Behaviour

I expect to be able to upgrade to newer neomutt release periodically, and have it accept my muttrc, or if it doesn't like something, I expect to at least see a non-blank error message.

## Actual Behaviour

```
Error in /home/mg/.mutt/muttrc, line 24: 
Error in /home/mg/.mutt/neomuttrc, line 2: source: file /home/mg/.mutt/muttrc could not be sourced
Error: 
Error in /home/mg/.mutt/neomuttrc, line 7: 
source: errors in /home/mg/.mutt/neomuttrc
```

Line 24 of ~/.mutt/muttrc is

```
set envelope_from=yes		# Pass -f<address> option to sendmail
```
Line 2 of ~/.mutt/neomuttrc is
```
source ~/.mutt/muttrc
```
Line 7 of ~/mutt/muttrc is
```
ifdef attach_keyword set attach_keyword = "\\<attach(|ed|ments?)\\>|priseg|prikabin"
```

## Steps to Reproduce

TBD

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?  20200626

## NeoMutt Version

```
NeoMutt 20200814
Copyright (C) 1996-2020 Michael R. Elkins ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 5.4.0-42-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
GnuTLS: 3.6.13
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --tokyocabinet --full-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Įprastos parinktys:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Kompiliavimo parinktys:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version  Ubuntu 20.04
* Were you using multiple copies of NeoMutt at once?  no
* Were you using 'screen' or 'tmux'?  no
* Is your email local (maildir) or remote (IMAP)?  local

**Comment by mgedmin** [comment] 2020-08-17 10:14
Some git archaeology told me that `envelope_from` was renamed to `use_envelope_from` back in 2005, with a compatibility synonym left over.

I guess my bug is solely about poor error reporting: neomutt never warned me that `envelope_from` is deprecated and is going to be removed, and when it was removed, the error message is blank instead of telling me what happened.

**Comment by flatcap** [comment] 2020-08-17 10:15
Ah!  This might be a problem with config synonyms in the send library.
I should be fixed in 149ef330c, which I pushed this morning.

**Comment by mgedmin** [comment] 2020-08-17 10:16
FWIW using `use_envelope_from` fixes half of my problem; there's still the error-message-less complaint about neomuttrc line 7 (attach_keyword).

**Comment by mgedmin** [comment] 2020-08-17 10:19
More git archaeology tells me `$attach_keyword` was renamed to `$abort_noattach_regex` back on 2018-03-20, and it's just that 20200626 never complained that I was setting an unknown option?

I guess I'm grateful for 20200814 letting me know about these old option names, but I wish it would tell me with _words_, in addition to the line number.

**Comment by flatcap** [comment] 2020-08-17 10:20
BUG: fixed, see above

**Comment by mgedmin** [comment] 2020-08-17 10:20
Ah, attach_keyword is also a synonym, which didn't work due to a bug.

**Comment by mgedmin** [comment] 2020-08-17 10:22
So, what's with the blank error messages?

**Comment by flatcap** [comment] 2020-08-17 10:25
The blank messages were caused by the config code returning unexpected values -- indicating code errors.
Which they were.  They won't happen again.

**Comment by mgedmin** [comment] 2020-08-19 09:48
Then I think this issue can be closed?

**Closed** 2020-08-19 09:50 UTC
Labels: type:bug
