### ISSUE TITLE
Cannot put configuration files in ~/.mutt folder anymore

### ISSUE THREAD

**Issue by antoyo** [neomutt/neomutt#1920] opened 2019-11-02 20:48 UTC
## Expected Behaviour

Load configuration like before.
I'm trying to load neomutt and HTML messages.

## Actual Behaviour

Theme does not load and HTML wont load in lynx as specified by `mailcap` file.
Error is:
```
Error in /home/bouanto/.neomuttrc, line 35: source: file ../.dotfiles/mutt/.mutt/theme could not be sourced
source: errors in /home/bouanto/.neomuttrc
```
line 35 being `source ~/.mutt/theme`.

Also, not sure why it always seem to pick a relative path starting with `../dotfiles/mutt/` when I use the `~/.mutt` directory.

It works when I use that instead:
```
source ~/.neomutt/theme
```

neomutt shows the following for an HTML-only message:

```
[-- text/html is unsupported (use 'r' to view this part) --]
```

**Edit:** Same here, using `set mailcap_path = ~/.neomutt/mailcap` fixes the problem for HTML emails.

## Steps to Reproduce

Add this to `.neomuttrc`:

```
source ~/.mutt/theme
set mailcap_path = ~/.mutt/mailcap
```

And create a theme and a mailcap file.
Mailcap file contains:
```
text/html; lynx -assume_charset=%{charset} -display_charset=utf-8 -dump %s; nametemplate=%s.html; copiousoutput
```

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
`NeoMutt 20191102`

## NeoMutt Version

```
NeoMutt 20191102
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: ArchLinux
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Local

**Comment by flatcap** [comment] 2019-11-03 02:39
Sorry @antoyo, I can't seem to repeat this.

I created a new user with just those files plus an html email:
```
Mail/cur
Mail/cur/1497110968.M698711P2101.flatcap.org,S=13285,W=13552:2,S
Mail/new
Mail/tmp

.mutt
.mutt/mailcap
.mutt/theme.rc

.neomuttrc
```

When I run NeoMutt, the theme is read and when I view the html part of the email, the mailcap file is used.

Do you have any symlinks in your directory tree?

**Comment by antoyo** [comment] 2019-11-03 13:35
@flatcap: Yes and something really weird just happened:
my config somehow got deleted (the three files).
Does the support of symlink changed?

**Comment by flatcap** [comment] 2019-11-03 13:44
> my config somehow got deleted

Argh!  I'm certain the config-reading code is read-only and couldn't have done that.

>  Does the support of symlink changed?

Sort of.  We 'fixed' a bug where symlinks weren't followed correctly.

Which files/dirs in your example were symlinks?

**Comment by antoyo** [comment] 2019-11-03 13:49
All of them:
```
~/.neomuttrc -> ~/.dotfiles/mutt/.neomuttrc
~/.mutt/mailcap -> ~/dotfiles/mutt/.mutt/mailcap
~/.mutt/theme -> ~/dotfiles/mutt/.mutt/theme
```

**Comment by flatcap** [comment] 2019-11-03 14:14
OK, thanks.  Now I see it.
If your symlinks were absolute `/home/user/.dotfile/...` then it would work.

For `dir/path -> ../target`, NeoMutt seems to look for `../target` in `.` rather than `dir`

```
.
├── .dotfiles
│   └── mutt
│       ├── mailcap
│       ├── .neomuttrc
│       └── theme
├── .mutt
│   ├── mailcap -> ../.dotfiles/mutt/mailcap
│   └── theme -> ../.dotfiles/mutt/theme
└── .neomuttrc -> .dotfiles/mutt/.neomuttrc
```

**Comment by protist** [comment] 2019-11-04 09:21
I've also hit this regression in a different situation. Previously, if you copy/save a message to a symlinked maildir, this worked fine. Let's say that `A` was the target for the symlink `B`. Previously, you could copy/save to `B` perfectly fine. Now, NeoMutt asks you if you want to create the maildir of the target `A`, even though it already exists. If you say yes, then it fails with
```
../main/Archives.2018: Permission denied (errno = 13)
```

**Comment by antoyo** [comment] 2019-11-04 12:57
@protist: Now that you talk of it…
I don't know if it is another issue, but I've seen something similar (unrelated to symlink, though):
If I have two neomutt opened, and I delete a message in one instance, close and exit, delete a message in the second instance, and close, I'll get an error:
```
Unable to write /path/to/mailbox
```

**Comment by flatcap** [comment] 2019-11-07 14:35
Please can you give the branch [[fix-relative-symlink-resolution-2]](https://github.com/neomutt/neomutt/tree/fix-relative-symlink-resolution-2) a try.

**Comment by antoyo** [comment] 2019-11-07 23:47
That does not fix it.
I get one more error (probably unrelated):
```
Error in /home/bouanto/.neomuttrc, line 35: source: file /home/bouanto/.mutt/theme could not be sourced
Error in /home/bouanto/.neomuttrc, line 42: ERR01 unknown variable: header_cache
source: errors in /home/bouanto/.neomuttrc
```

**Comment by flatcap** [comment] 2019-11-08 00:26
> Error in /home/bouanto/.neomuttrc, line 42: ERR01 unknown variable: header_cache

Yes, that's just from building without a header cache backend, e.g. tokyocabinet.

> That does not fix it.

OK, may we change your file layout to:
```
.
├── .dotfiles
│   └── mutt
│       ├── mailcap
│       ├── neomuttrc
│       └── theme
└── .mutt -> .dotfiles/mutt
```

All the files are in your dotfiles repo.
All the config works either absolutely, through `~/.mutt/XXX`,
or relatively: `neomuttrc` can safely `source theme` (without a path).

**Comment by protist** [comment] 2019-11-08 05:31
> Please can you give the branch [[fix-relative-symlink-resolution-2]](https://github.com/neomutt/neomutt/tree/fix-relative-symlink-resolution-2) a try.

I can confirm that this fixes my problem of symlinked maildirs at least.

**Comment by antoyo** [comment] 2019-11-08 12:36
I changed my layout to:
```
.config/neomutt/
├── mailcap -> ../../.dotfiles/neomutt/.config/neomutt/mailcap
├── neomuttrc -> ../../.dotfiles/neomutt/.config/neomutt/neomuttrc
└── theme -> ../../.dotfiles/neomutt/.config/neomutt/theme
.dotfiles/neomutt/
└── .config
    └── neomutt
        ├── mailcap
        ├── neomuttrc
        └── theme
```
And now everything seems to work except the mailcap.
Could there be something missing for the symlink in the mailcap path resolution?

**Comment by flatcap** [comment] 2019-11-08 12:45
I think you're still making it more complicated than it needs to be.
With your scheme, if you add a new config file, you need to add a new symlink.

I'd try linking the **dir**, not the files:

```
.config/neomutt/ -> ../.dotfiles/neomutt
.dotfiles/neomutt/
└── .config
    └── neomutt
        ├── mailcap
        ├── neomuttrc
        └── theme
```

> I guess we can close this issue.

Thank you :-)

**Comment by mgedmin** [comment] 2019-11-08 14:32
Ironically I was motivated to create the PR fixing this because my ~/.mailcap symlink wasn't working in #1937.

Can you use `strace -o /tmp/trace.log neomutt` and then grep mailcap /tmp/trace.log to see where mutt is trying to look for it?

**Comment by antoyo** [comment] 2019-11-08 23:58
@mgedmin On master or in the branch?

**Comment by mgedmin** [comment] 2019-11-09 08:57
The branch has been merged into master AFAIU.

**Comment by antoyo** [comment] 2019-11-09 13:03
@mgedmin: I'm not sure what you want me to try, then, because it worked with this branch.

**Comment by mgedmin** [comment] 2019-11-09 18:51
> @mgedmin: I'm not sure what you want me to try, then, because it worked with this branch.

Uh, I mean when [you said](https://github.com/neomutt/neomutt/issues/1920#issuecomment-551318968):

> That does not fix it.

I thought you were testing the branch?

I know you later found a symlink configuration that works, but I'm wondering now if there's still some situation where things break.

**Comment by antoyo** [comment] 2019-11-09 19:25
I thought there was still something wrong, but I tested again with the master branch and my previous folder structure now works.

**Closed** 2023-12-21 08:14 UTC
Labels: bug:confirmed
