### ISSUE TITLE
neomutt doesn't show directory listing

### ISSUE THREAD

**Issue by jpritikin** [neomutt/neomutt#2360] opened 2020-05-26 15:43 UTC
## Expected Behaviour

It should show a directory listing when I hit tab

## Actual Behaviour

I recorded a video showing how I can't get a list of directories, https://youtu.be/ansYisjJViw

If NeoMutt crashed, did your OS create a 'coredump' file?  Doesn't crash

## Steps to Reproduce

See video above

## How often does this happen?

- Always

## When did it start to happen?

I think it started when I upgraded ubuntu to Focal. Not sure though.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-7626-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-WmwApX/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Operating System and its version: Ubuntu Focal, amd64
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Maildir

I reported the issue [here](https://bugs.launchpad.net/ubuntu/+source/neomutt/+bug/1878068) too

**Comment by scottkosty** [comment] 2020-06-04 23:43
Thanks for taking the time to write up those details. I think the issue is the same as reported at https://github.com/neomutt/neomutt/issues/2199#issuecomment-609448434 and is fixed in master. Do you feel like trying to compile master to confirm that it's fixed? We can help you figure out how to compile in case you're interested.

**Comment by jpritikin** [comment] 2020-06-05 00:59
I built 8e5320210a3705 from source. The bug is no longer present. Thank you. What a relief!

**Comment by scottkosty** [comment] 2020-06-05 01:57
Great, thanks for confirming!

**Closed by scottkosty** 2020-06-05 01:57 UTC
