### ISSUE TITLE
"folder-hook . exec collapse-all" doesn't execute on startup

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#227] opened 2016-11-07 19:38 UTC
100% reproducible when using [i3wm](http://i3wm.org) and [urxvt](https://packages.debian.org/search?keywords=rxvt-unicode) (also sometimes with xterm and gnome-terminal).

not sure if mutt's bug. maybe it's i3's issue? 
happens with and without neomutt patches.

minimal setup for reproduction: 

**test.muttrc**
```
set folder = /tmp
set spoolfile = test.mbox
set sort = threads
folder-hook . exec collapse-all
```

**test.mbox**
```
From nobody@example.com Sat Sep 10 10:39:15 2016
Message-ID: <parent>
Subject: parent
Status: O
Content-Length: 0
Lines: 0


From nobody@example.com Sun Sep 11 10:33:11 2016
Message-ID: <child>
Subject: child
References: <parent>
Status: O
Content-Length: 0
Lines: 0

```

**okay.rc**
```
env -i TERM=rxvt /usr/local/bin/mutt -F test.muttrc
```

**fail.rc**
```
urxvt -e /bin/bash -c 'env -i TERM=rxvt /usr/local/bin/mutt -F test.muttrc'
```

`env -i` clears all environment varibles to rule out somekind of interference from there.

save all files into same directory, cd into it and execute `./okay.rc` and `./fail.rc`.

**Comment by d-k-c** [comment] 2016-11-07 19:42
Idem, issue 100% reproducible in the environment described by 4nd3r. I'll try to take a look at it.

**Comment by 4nd3r** [comment] 2016-11-12 10:22
also happens with `folder-hook . exec middle-page`

**Comment by guyzmo** [comment] 2017-02-26 16:32
* is it still happening?
* @d-k-c any ideas?
* have anyone tried to hack the code to add a log point at where the folder-hook is running and see if it actually gets called?

has a bug been opened in upstream?

**Comment by d-k-c** [comment] 2017-02-27 21:05
Didn't really find anything during my first tests and then kind of forgot about it.

**Comment by d-k-c** [comment] 2017-04-20 14:01
I've found the cause of this bug:

the "macro event" is pushed with `mutt_push_macro_event` and stored in the `MacroEvents` array. But with fail.rc, this array is emptied before it's executed through a call to `mutt_flushinp`, originating from [curs_main.c#L1033](https://github.com/neomutt/neomutt/blob/master/curs_main.c#L1033). In that case, we have `Sigwinch == 1`, whereas it's equal to 0 with okay.rc.

I still don't know why the behaviour is different between the two commands, and the answer might be in i3 and/or urxvt.

**Comment by nobrowser** [comment] 2017-04-26 06:17
I use urxvt exclusively, with openbox.  I have never seen this behavior.

Wild guess: the window manager resizes the terminal window after it is created?

**Comment by 4nd3r** [comment] 2017-04-29 13:27
> Wild guess: the window manager resizes the terminal window after it is created?

@Airblader, can you comment on this?

**Comment by Airblader** [comment] 2017-04-29 14:08
I don't understand the issue since I'm not familiar with mutt, but as far as the question goes: yes, of course the window manager resizes the window after it is created. It can hardly do that before the window exists. :-) 

However, i3 will resize it *before* it maps(!) the window. Either way, no X client should have a problem with being resized. 

From my limited understanding of the issue I'm not sure what this has to do with X, though? It seems to be something purely inside neomutt or am I wrong?

**Comment by d-k-c** [comment] 2017-04-29 20:56
I commented that on IRC but forgot to add it here: the issue is way harder to reproduce when running with `-d 2` (actually, any level). I didn't really check why though, but a wild guess is that SIGWINCH is delivered before we install the signal handler with okay.rc, but not with fail.rc.

I won't spend more time tracking down the reason why we get the signal in one case and not the other because the benefit/time ratio is quite low; but we could check why MacroEvents get flushed in that case, and remove that if it doesn't make sense.

**Comment by guiniol** [comment] 2017-04-30 16:43
I just want to add that I use i3 and urxvt and I have never seen that. I don't think it's simply urxvt + i3, or at least, could be related to config/compilation options.

**Comment by krims0n32** [comment] 2017-06-13 21:48
Same issue with i3wm, urxvt & push in muttrc.

**Comment by flatcap** [comment] 2017-07-03 09:24
What's the status of this issue?
Is anyone still investigating?
If not, I will close this as a known bug.

**Comment by 4nd3r** [comment] 2017-07-03 09:50
not investigating, but still experiencing it :<

**Comment by oblitum** [comment] 2017-09-13 00:35
This happens for me in completely different environment. I'm on termite, running Gnome on ArchLinux. The trick is, this seems to be related with how I start mutt, if I start it myself, generally no issue as far as I remember, but when I start it through a tmuxp recipe (a tmux manager for quickly opening/managing work sessions), it does start with all threads uncollapsed. I've also found a really old thread that mentions this behavior when mutt was started from a script http://mutt-users.mutt.narkive.com/66wZmeUg/collapse-all-folder-hook-doesn-t-alway-work-for-default-mailbox.

**Comment by flatcap** [comment] 2017-10-04 01:37
I think I've found and fixed this problem ([description here](https://github.com/neomutt/neomutt/pull/818#issue-262641001)).

Please can you give [[issue/227](https://github.com/neomutt/neomutt/tree/issue/227)] a try.

**Comment by oblitum** [comment] 2017-10-04 05:06
@flatcap I've tried the branch and the issue doesn't happen anymore, so it seems fixed 🙂

**Comment by 4nd3r** [comment] 2017-10-04 06:18
thank you for your effort, but not for me :(

**Closed** 2017-11-30 13:10 UTC
Labels: bug:upstream, needs:info-from-user, status:new-bug, type:bug
