### ISSUE TITLE
color sidebar_flagged not work

### ISSUE THREAD

**Issue by santimoreno** [neomutt/neomutt#576] opened 2017-05-08 10:33 UTC
* **bug reports**
When I define color to sidebar_flagged apply it the color from sidebar_highlight and no the my custom color for this.
    * Used program versions
NeoMutt 1.8.1
    * Operating System and its version
Debian 8.8

**Comment by toogley** [comment] 2017-05-08 14:15
@santimoreno could you please give the exact neomutt version? It usually looks like that `NeoMutt 20170428-2-135b1b (1.8.2)` or similar. Thanks.

**Comment by riesebie** [comment] 2017-05-08 17:55
@santimoreno if you browse to the folder which contains flagged mails the sidebar_highlight colour is preferred. Just scroll away from your "flagged folder" and check again. The sidebar_flagged colour works fine here with NeoMutt 20170428-lxtec (1.8.2). BTW you get the exact version of your NeoMutt by typing `mutt -vv | head -1`

**Comment by riesebie** [comment] 2017-05-08 17:59
Sorry for closing by accident.

**Comment by santimoreno** [comment] 2017-05-15 08:25
The exact neomutt version is 20170414-19-98e1ed4 (1.8.1). @riesebie the colour change to sidebar_highlight when I browse the folder with flagged but when I change to other folder the colour for folder with flagged isn't the set in muttrc for sidebar_flagged.
This is the color part from my muttrc:
```
# SIDEBAR -----------------------------------------------------------
color sidebar_spoolfile brightcolor244  color235
color sidebar_divider   color172        color235
color sidebar_flagged   color220        color235
color sidebar_highlight color235        color172
color sidebar_indicator brightcolor172  color235
color sidebar_new       color28         color235
color sidebar_ordinary  color244        color235
```
and this the result:
![screenshot from 2017-05-15 10-24-56](https://cloud.githubusercontent.com/assets/14818822/26048772/caa9889c-3958-11e7-8345-85b1ddb7a364.png)

**Comment by flatcap** [comment] 2017-05-15 10:58
@santimoreno 
OK, what you're seeing is the expected behaviour (both here and in upstream mutt).
The code can only apply one highlight colour to the each folder in the sidebar.
Folders containing new mail are "more important" than folders with flagged mail.

You can see the [priority order](https://github.com/neomutt/neomutt/blob/d7f0ba48a0ba4476084d83b9242c2f5661491125/sidebar.c#L833-L855) in the code.

- indicator
- highlight
- new
- flagged
- spoolfile
- ordinary
- normal

Unfortunately, it's not configurable.

**Comment by santimoreno** [comment] 2017-05-15 17:19
Sorry @flatcap but I don't understand it. The folders in **brightred** (I don't know from where this colour it's set) don't have any new mail, the number in bracket are flagged messages. The colour set for sidebar_flagged is color220 (yellow). I try with other version (20170113 (1.7.2)) and it works well. This is a capture with the same muttrc:
![captura de pantalla de 2017-05-15 19-19-11](https://cloud.githubusercontent.com/assets/14818822/26070048/6ac74658-39a3-11e7-9303-a30cd2841922.png)

**Comment by flatcap** [comment] 2017-07-03 10:18
Ah, I see what you mean.
I've tried your config and I get the colours that you'd **expect**.

There's no default colour in the code, so there aren't many possible explanations.
This colour script will show the terminal's colours.
What colour do you see for '220'?

```sh
#!/bin/bash
for ((y = 0; y < 32; y++)); do
    for ((x = 0; x < 8; x++)); do
        NUM=$((x*32+y))
        printf "%4d \e[%d;5;%dmXXX\e[0m" $NUM 38 $NUM
    done
    echo
done
```

**Closed** 2017-12-04 15:48 UTC
Labels: type:question
