### ISSUE TITLE
Binding 'gg' will alias 'g'

### ISSUE THREAD

**Issue by magnetophon** [neomutt/neomutt#643] opened 2017-06-22 09:40 UTC
* **bug reports**

Since upgrading neomutt to 1.8.3, I get two warnings on startup:
```
Warning in /home/bart/.mutt/neomuttrc, line 80: Binding 'gg' will alias 'g'
Warning in /home/bart/.mutt/neomuttrc, line 144: Binding 'gg' will alias 'g'
```
 * Steps to reproduce
put the following in your neomuttrc:
```
bind index gg       first-entry
bind pager gg top
``` 

 * Used program versions 
1.8.3 2017060220170602

 * Operating System and its version
NixOS 17.09pre

**Comment by flatcap** [comment] 2017-06-22 09:56
Yes, that's a warning we introduced so that users know when bindings won't work.
https://www.neomutt.org/guide/configuration.html#bind-warnings

Closing as a dupe of #621

**Closed by flatcap** 2017-06-22 09:56 UTC
Labels: closed:duplicate, type:question
