### ISSUE TITLE
Mailboxes list in the sidebar has gone haywire after upgrading

### ISSUE THREAD

**Issue by jefx07** [neomutt/neomutt#2743] opened 2020-12-01 22:46 UTC
Hi,

For several years I've had multiple accounts set up utilizing `folder-hook`s to source different files with settings unique for each account. Recently I also separated the `mailboxes` for each account and include `unmailboxes *` above them to clear the previous accounts list. This has been working fine until ugrading to 2020-11-20 when the mailbox list in the sidebar started behaving strangely.

By strangely I mean when I switch accounts I will end up with duplicate Inboxes in the sidebar, then if I change folders I might have 2 Sent folders and 2 Inbox folders, for example, and if I continue to switch between accounts or change folders I might end up with 3, 4 or 5 Inbox, Sent or Archive folders etc. in the sidebar.

I've noticed if I uncomment `unmailboxes *` from each file then things settle down but then I may as well just have a global `mailboxes` list instead (as switching accounts appends the new mailboxes to the bottom of the previous accounts in the sidebar).

Downgrading to 2020-09-25 fixes the weirdness.

_Oh, first time reporting a possible issue and hope I've explained things okay and correctly._

**Comment by gahr** [comment] 2020-12-02 06:10
Does it look like unmailboxes does’t remove the currently selected mailbox?  Rings a bell.. let me look into it.

**Comment by gahr** [comment] 2020-12-02 06:56
I can't reproduce this. Can you please provide more details on your setup with sample config files?

**Comment by jefx07** [comment] 2020-12-02 08:35
Yes sure, I'm don't know which config files you need so I've attached all of them plus output of `neomutt -v` . If you need any other info please ask.

[neomutt-settings.zip](https://github.com/neomutt/neomutt/files/5627896/neomutt-settings.zip)

**Comment by gahr** [comment] 2020-12-02 10:46
I have kind of reproduced your config at my side. I still can't reproduce the bug, but I have identified a crash. I think there's something odd along these lines:

1. change-folder creates a mailbox
2. folder-hook gets triggered
2.1 `source` the file containing `unmailboxes *` and `mailboxes ...`
2.2. mailboxes are created, linked to the account, and added to the sidebar
3. the code finishes up adding the mailbox
3.1 the mailbox is added to the sidebar (**here the double entry**)

I can't repro that exact sequence and I'm looking into the crash, but I have a hunch that fixing the crash will resolve your problem too. I'll keep you posted.

**Comment by jefx07** [comment] 2020-12-02 11:07
Thank you very much, I hope I'm not putting you to too much trouble. It does seem it was introduced beginning with the 2020-11-20 release (although I didn't notice it until upgrading to 2020-11-27), maybe there were some changes made to the relevant code at that time.

**Comment by gahr** [comment] 2020-12-02 11:10
Would you be able to test the devel/issue-2743 branch out?

**Comment by jefx07** [comment] 2020-12-02 11:35
I've just tested the devel/issue-2743 branch and that seems to have fixed the problem for me, I'm _not_ getting multiplying mailboxes any more. Many thanks gahr!

**Comment by gahr** [comment] 2020-12-02 11:50
phew that's great news, thanks for testing!

**Comment by jefx07** [comment] 2020-12-02 12:05
No problem. Sorry I don't know what's the correct the protocol, is it up to me to close the issue now or do I leave it to you to do, with anything else that may be required?

**Comment by gahr** [comment] 2020-12-02 12:47
I'll let the merging of the PR close the issue automatically, thanks!

**Closed** 2020-12-04 09:09 UTC
Labels: bug:confirmed, closed:fixed
