### ISSUE TITLE
change-vfolder does not suggest an unread mailbox

### ISSUE THREAD

**Issue by iliastsi** [neomutt/neomutt#1982] opened 2019-11-20 15:45 UTC
## Expected Behaviour

`change-vfolder` should suggest a mailbox with unread messages like this:

 `Open mailbox ('?' for list):  Dummy`

## Actual Behaviour

It does not auto-complete any mailbox:

`Open mailbox ('?' for list): `

## How often does this happen?

- Always

## When did it start to happen?

I bisected it and the regression was introduced in commit 4e5d94bc.

## NeoMutt Version

```
NeoMutt 20191111
```

**Comment by roccoblues** [comment] 2023-12-21 08:19
Hi, I'm trying to cleanup some older issues here. Can you still reproduce this behavior with the latest version? Thanks!

**Comment by iliastsi** [comment] 2023-12-21 09:02
Hi @roccoblues, I currently use `20231103` and this bug is still present.

**Comment by roccoblues** [comment] 2023-12-21 09:19
Thanks for the quick feedback. Looks like @Austin-Ray already created a fix. I'll try to find out why it was never merged. 

If you like you can give the [roccoblues/next-mailbox-nm](https://github.com/neomutt/neomutt/tree/roccoblues/next-mailbox-nm) brach a try. It should fix the issue.

**Comment by roccoblues** [comment] 2023-12-21 13:36
As discussed with @flatcap on IRC: the check was added in 212eadf75. At that time the notmuch mailboxes were entirely separate from maildir. That changed later, so probably this check is no longer necessary.

**Closed** 2023-12-23 15:36 UTC
Labels: type:bug, topic:notmuch
