### ISSUE TITLE
GCC 4.2 warnings following conversion of macros to inline functions

### ISSUE THREAD

**Issue by sthen** [neomutt/neomutt#432] opened 2017-02-25 10:13 UTC
https://github.com/neomutt/neomutt/commit/dca6feacfd242f70842d3728945e02dcd802f7e6 converts macros to inline functions, however with GCC 4.2 this results in a bunch of warnings:

```
mutt.h:655: warning: C99 inline functions are not supported; using GNU89
mutt.h:655: warning: to disable this warning use -fgnu89-inline or the gnu_inline function attribute
mutt.h:660: warning: C99 inline functions are not supported; using GNU89
mutt.h:665: warning: C99 inline functions are not supported; using GNU89
mutt.h:737: warning: C99 inline functions are not supported; using GNU89
mutt.h:749: warning: C99 inline functions are not supported; using GNU89
mutt.h:933: warning: C99 inline functions are not supported; using GNU89
```

**Comment by toogley** [comment] 2017-02-25 10:23
@sthen thanks for reporting.

**Comment by gahr** [comment] 2017-02-25 17:05
Wow, gcc 4.2, the last release from that series was 9 years ago. From the [release notes](https://gcc.gnu.org/gcc-4.2/changes.html):

"In the next release of GCC, 4.3, -std=c99 or -std=gnu99 will direct GCC to handle inline functions as specified in the C99 standard. In preparation for this, GCC 4.2 will warn about any use of non-static inline functions in gnu99 or c99 mode. This new warning may be disabled with the new gnu_inline function attribute or the new -fgnu89-inline command-line option. Also, GCC 4.2 and later will define one of the preprocessor macros __GNUC_GNU_INLINE__ or __GNUC_STDC_INLINE__ to indicate the semantics of inline functions in the current compilation."

@sthen Any chance you can migrate to a newer compiler? Also, I'd be interested in seeing the output of your autoconf stage (`./prepare` or `./configure`), as I really think old compilers like this should be detected and reported as an error since they don't fully support C99.

**Comment by gahr** [comment] 2017-02-25 18:07
I'm tempted to close this as "not-a-bug"..

**Comment by guyzmo** [comment] 2017-02-25 18:14
though +1 on warning against old compilers loudly at compile time

**Comment by gahr** [comment] 2017-02-26 12:26
I have been able to test on FreeBSD/sparc with gcc 4.2.1, autoconf correctly figures out the `-std=gnu99` switch.

```
checking for gcc option to accept ISO C99... -std=gnu99
```

I cannot reproduce.

**Comment by guyzmo** [comment] 2017-02-26 13:18
@sthen could you give more details on the system you're running?

**Comment by sthen** [comment] 2017-03-02 17:31
This is with GCC 4.2.1 (i.e. the last GPLv2 release) which is the system compiler on OpenBSD for most architectures at present. The majority of C programs in the ports tree are OK with this (the main reason for using a different compiler is c++11). autoconf does pick up -std=gnu99 but it also needs either -fgnu89-inline or using an attribute to avoid the warnings.

It's possible to build with a different compiler but not worth it ports-wise just for warnings.

```
cc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I.. -I../intl  -I/usr/local/include -I../intl  -Wall -pedantic -Wno-long-long -O2 -pipe -g -MT auth.o -MD -MP -MF .deps/auth.Tpo -c -o auth.o auth.c
In file included from auth.c:27:
../mutt.h:655: warning: C99 inline functions are not supported; using GNU89
../mutt.h:655: warning: to disable this warning use -fgnu89-inline or the gnu_inline function attribute
../mutt.h:660: warning: C99 inline functions are not supported; using GNU89
../mutt.h:665: warning: C99 inline functions are not supported; using GNU89
../mutt.h:737: warning: C99 inline functions are not supported; using GNU89
../mutt.h:749: warning: C99 inline functions are not supported; using GNU89
../mutt.h:933: warning: C99 inline functions are not supported; using GNU89
In file included from auth.c:27:
../mutt.h:1135: warning: C99 inline functions are not supported; using GNU89
```


Here's the output from autoconf:

```
checking for a BSD-compatible install... /usr/obj/ports/neomutt-20170225/bin/install -c 
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... mkdir -p
checking for gawk... (cached) awk
checking whether make sets $(MAKE)... (cached) yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... (cached) o
checking whether we are using the GNU C compiler... (cached) yes
checking whether cc accepts -g... (cached) yes
checking for cc option to accept ISO C89... none needed
checking whether cc understands -c and -o together... yes
checking dependency style of cc... gcc3
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for egrep... (cached) /usr/bin/egrep
checking for ANSI C header files... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking for strings.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-unknown-openbsd6.0
checking host system type... x86_64-unknown-openbsd6.0
checking for prefix... /usr/local
checking for gcc... (cached) cc
checking whether we are using the GNU C compiler... (cached) yes
checking whether cc accepts -g... (cached) yes
checking for cc option to accept ISO C89... (cached) none needed
checking whether cc understands -c and -o together... (cached) yes
checking dependency style of cc... (cached) gcc3
checking for cc option to accept ISO C99... -std=gnu99
checking for library containing strerror... none required
checking how to run the C preprocessor... cc -E
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... (cached) ranlib
checking for ar... (cached) ar
checking for inline... inline
checking for an ANSI C-conforming const... (cached) yes
checking whether byte ordering is bigendian... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking size of off_t... 8
checking for dbx... no
checking for gdb... /usr/bin/gdb
checking for sdb... no
checking for inttypes.h... (cached) yes
checking for uint32_t... yes
checking size of short... (cached) 2
checking size of int... 4
checking size of long... 8
checking size of long long... (cached) 8
checking for unsigned long long int... yes
checking for long long int... yes
checking for sendmail... /usr/sbin/sendmail
checking for gpgme-config... /usr/local/bin/gpgme-config
checking for ispell... /usr/local/bin/ispell
checking for initscr... no
checking for waddnwstr in -lncursesw... yes
checking for initscr in -lncursesw... yes
checking for tgetent in -lncursesw... yes
checking ncursesw/ncurses.h usability... no
checking ncursesw/ncurses.h presence... no
checking for ncursesw/ncurses.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking for start_color declaration... yes
checking for typeahead declaration... yes
checking for bkgdset declaration... yes
checking for curs_set declaration... yes
checking for meta declaration... yes
checking for use_default_colors declaration... yes
checking for resizeterm declaration... yes
checking for use_extended_names... yes
checking for ANSI C header files... (cached) yes
checking for stdarg.h... (cached) yes
checking for sys/ioctl.h... (cached) yes
checking ioctl.h usability... no
checking ioctl.h presence... no
checking for ioctl.h... no
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking for sys/time.h... (cached) yes
checking for sys/resource.h... (cached) yes
checking for sys/syscall.h... (cached) yes
checking unix.h usability... no
checking unix.h presence... no
checking for unix.h... no
checking for setrlimit... (cached) yes
checking for getsid... (cached) yes
checking for fgets_unlocked... no
checking for fgetc_unlocked... no
checking for strcasecmp... (cached) yes
checking for strncasecmp... (cached) yes
checking for setenv... (cached) yes
checking for strdup... (cached) yes
checking for strsep... (cached) yes
checking for strtok_r... (cached) yes
checking for mkdtemp... yes
checking for sig_atomic_t in signal.h... yes, non volatile
checking whether sys_siglist is declared... yes
checking for pid_t... (cached) yes
checking for ssize_t... (cached) yes
checking for fgetpos... (cached) yes
checking for memmove... (cached) yes
checking for setegid... (cached) yes
checking for srand48... (cached) yes
checking for strerror... (cached) yes
checking for wcscasecmp... yes
checking for strcasestr... yes
checking for getopt... (cached) yes
checking for getopt.h... (cached) yes
checking for va_copy... va_copy
checking for ftruncate... (cached) yes
checking for strftime... (cached) yes
checking for futimens... (cached) yes
checking for fchdir... (cached) yes
checking for regcomp... (cached) yes
checking whether your system's regexp library is completely broken... no
checking where new mail is stored... /var/mail
checking if /var/mail is world writable... no
checking if /var/mail is group writable... no
checking where to put the documentation... /usr/local/share/doc/mutt
checking for gethostent... (cached) yes
checking for setsockopt... (cached) yes
checking for getaddrinfo... (cached) yes
checking for library containing getaddrinfo_a... no
checking for sys/select.h... (cached) yes
checking for socklen_t... yes
checking for deflate in -lz... (cached) yes
checking for X509_STORE_CTX_new in -lcrypto... yes
checking for SSL_new in -lssl... yes
checking for RAND_status... yes
checking for RAND_egd... no
checking whether SSL_set_mode is declared... yes
checking whether SSL_MODE_AUTO_RETRY is declared... yes
checking whether struct dirent defines d_ino... yes
checking kclangc.h usability... yes
checking kclangc.h presence... yes
checking for kclangc.h... yes
checking for kcdbopen in -lkyotocabinet... yes
checking for library containing strerror... (cached) none required
checking for off_t... (cached) yes
checking for size_t... (cached) yes
checking for working alloca.h... (cached) no
checking for alloca... (cached) yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... (cached) yes
checking for working mmap... (cached) yes
checking whether we are using the GNU C Library 2.1 or newer... no
checking argz.h usability... no
checking argz.h presence... no
checking for argz.h... no
checking for limits.h... (cached) yes
checking for locale.h... (cached) yes
checking for nl_types.h... (cached) yes
checking for malloc.h... (cached) no
checking for stddef.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for feof_unlocked... no
checking for fgets_unlocked... (cached) no
checking for getcwd... (cached) yes
checking for getegid... (cached) yes
checking for geteuid... (cached) yes
checking for getgid... (cached) yes
checking for getuid... (cached) yes
checking for mempcpy... no
checking for munmap... (cached) yes
checking for putenv... (cached) yes
checking for setenv... (cached) yes
checking for setlocale... (cached) yes
checking for stpcpy... (cached) yes
checking for strchr... (cached) yes
checking for strcasecmp... (cached) yes
checking for strdup... (cached) yes
checking for strtoul... (cached) yes
checking for tsearch... (cached) yes
checking for __argz_count... no
checking for __argz_stringify... no
checking for __argz_next... no
checking for iconv... yes
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for nl_langinfo and CODESET... yes
checking for LC_MESSAGES... yes
checking whether NLS is requested... yes
checking whether included gettext is requested... no
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for GNU gettext in libc... no
checking for GNU gettext in libintl... yes
checking for dcgettext... yes
checking for msgfmt... /usr/local/bin/msgfmt
checking for gmsgfmt... /usr/local/bin/msgfmt
checking for xgettext... /usr/local/bin/xgettext
checking for bison... bison
checking version of bison... 3.0.4, ok
checking for catalogs to be installed...  bg ca cs da de el en_GB eo es et eu fr ga gl hu id it ja ko lt nl pl pt_BR ru sk sv tr uk zh_CN zh_TW
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
checking whether iconv.h defines iconv_t... yes
checking whether this iconv is good enough... yes
checking whether iconv is non-transcribing... no
checking for bind_textdomain_codeset... yes
checking stringprep.h usability... yes
checking stringprep.h presence... yes
checking for stringprep.h... yes
checking idna.h usability... yes
checking idna.h presence... yes
checking for idna.h... yes
checking for library containing stringprep_check_version... -lidn
checking for idna_to_unicode_utf8_from_utf8... no
checking for idna_to_unicode_8z8z... yes
checking for idna_to_ascii_from_utf8... no
checking for idna_to_ascii_8z... yes
checking for idna_to_ascii_lz... yes
checking for idna_to_ascii_from_locale... no
checking for wchar.h... (cached) yes
checking for wchar_t... yes
checking for wint_t... yes
checking for wctype.h... (cached) yes
checking for iswalnum... yes
checking for iswalpha... yes
checking for iswblank... (cached) yes
checking for iswcntrl... (cached) yes
checking for iswdigit... yes
checking for iswgraph... yes
checking for iswlower... yes
checking for iswprint... yes
checking for iswpunct... yes
checking for iswspace... yes
checking for iswupper... yes
checking for iswxdigit... yes
checking for towupper... yes
checking for towlower... yes
checking for mbstate_t... yes
checking for wchar_t functions... yes
checking for nl_langinfo and CODESET... yes
checking for nl_langinfo and YESEXPR... yes
checking for fmemopen... yes
checking for open_memstream... yes
checking for ospcat... none
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/Makefile
config.status: creating doc/Makefile
config.status: creating imap/Makefile
config.status: creating intl/Makefile
config.status: creating m4/Makefile
config.status: creating po/Makefile.in
config.status: creating hcachever.sh
config.status: creating doc/instdoc.sh
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing default-1 commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
configure: WARNING: unrecognized options: --disable-gtk-doc
configure: Summary of build options:

  Version:           20170225
  Host OS:           openbsd6.0
  Install prefix:    /usr/local
  Compiler:          cc -std=gnu99
  CFlags:            -Wall -pedantic -Wno-long-long -O2 -pipe -g -I/usr/local/include -I$(top_srcdir)/intl
  LDFlags:           -L/usr/local/lib
  Libs:              -lncursesw 
  Mutt libs:          -lncursesw -lssl -lcrypto -lz -lkyotocabinet -lidn 

  GPGME:             no
  PGP:               yes
  SMIME:             yes
  Sidebar:           yes
  Notmuch:           no
  Compressed Folder: yes
  Header Cache(s):   kyotocabinet 

  POP3:              yes
  IMAP:              yes
  NNTP:              yes
  SMTP:              yes
```

**Comment by sthen** [comment] 2017-03-02 17:41
...hmm, actually, they're not just warnings - linking fails.

```/usr/obj/ports/neomutt-20170225/neomutt-20170225/mutt.h:1136: multiple definition of `mutt_new_enter_state'
addrbook.o:/usr/obj/ports/neomutt-20170225/neomutt-20170225/mutt.h:1136: first defined here
alias.o: In function `mutt_new_header':
/usr/obj/ports/neomutt-20170225/neomutt-20170225/mutt.h:934: multiple definition of `mutt_new_header'
addrbook.o:/usr/obj/ports/neomutt-20170225/neomutt-20170225/mutt.h:934: first defined here
```
etc.etc.

I'm going to just patch them to static inline for now so I can update the port.

**Comment by nobrowser** [comment] 2017-03-02 18:59
I think we ought to require c99 at least (not necessarily gnu99), right at configure time.  If we don't, there will be surprises when code has c99 features.

**Comment by guyzmo** [comment] 2017-03-02 19:23
we do, so even if for the time being it's ok with some patches, there's going to be a point where it'll break. You should better switch either to GLP3 Gcc or to Clang to build neomutt.

**Comment by gahr** [comment] 2017-03-02 19:43
@sthen I can get access to an openbsd box and figure it out. Strange on freebsd/sparc/gcc 4.2.1 I couldn't reproduce.

**Comment by gahr** [comment] 2017-03-03 18:46
In FreeBSD we have a patched version of gcc 4.2.1. This could be the reason I cannot reproduce.

That being said, I think we could safely get a half step back and turn those functions into static inlines. This is not to fully retract the C99 support commitment, but it would be nice and fair to those forced to use an old compiler. Being gcc 4.2.1 the latest in the gpl2 series does indeed have important consequences. I'd be happy to do the job.
What do people think?

**Comment by toogley** [comment] 2017-03-03 20:24
> That being said, I think we could safely get a half step back and turn those functions into static inlines. This is not to fully retract the C99 support commitment, but it would be nice and fair to those forced to use an old compiler.

@ghar do you think of this as a temporary solution or as permanent?

**Comment by guyzmo** [comment] 2017-03-03 21:14
Well, I believe this can be ok for now, but what I'm afraid is that this might make a precedent to keep our code GCC 4.2 compatible, and make it a habit to fall back from C99 features to old GNU features. It's sad for those left on the side, but Neomutt with C99 will still be compilable with GPL3 GCC for exotic architectures and non GPL3 ones for the main ones.

[A note from Miod Vallat on the compiler topic dated 2013](http://marc.info/?l=openbsd-misc&m=137530560232232&w=2).

**Comment by gahr** [comment] 2017-03-06 07:25
I'd have the discussion on a case-by-case basis. Of course I don't want to stop us from using new features when they ease development. On the other hand, I this particular case, it's no harm to use static inlines instead.

**Closed** 2017-03-06 14:01 UTC
Labels: status:new-bug, type:bug
