### ISSUE TITLE
Message externally deleted from Maildir no longer disappears from index

### ISSUE THREAD

**Issue by lonerr** [neomutt/neomutt#2150] opened 2020-02-24 15:41 UTC
When neomutt detects that new message was removed from local Maildir it correctly reports: "Mailbox was externally modified. Flags may be wrong." But the message still presents in the index. Trying to open it leads to "Could not copy message" error. The only way to get rid of the error is restarting neomutt. 

Previously the same message "Mailbox was externally modified. Flags may be wrong." was also shown but the deleted message correctly disappeared from the index.

The bug appeared after upgrade from 20180716 to 20191207.

**Comment by jindraj** [comment] 2020-02-27 07:31
similar issue [imapfilter inbox index issue](#2077)

**Comment by gahr** [comment] 2020-03-02 09:58
Closing as duplicate of #2077.

**Closed by gahr** 2020-03-02 09:58 UTC
