### ISSUE TITLE
Mutt fails to handle RFC 2047 encoded words that are split in the middle of a multi-byte UTF-8 character

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#1015] opened 2017-12-21 08:56 UTC
My electricity provider sent me a Christmas message with the following Subject header:

```
Subject: =?UTF-8?Q?Kvie=C4=8Diame=20drauge=20pildyti=20ESO=20pasi=C5=BEad=C4?=
 =?UTF-8?Q?=97jim=C5=B3=20girliand=C4=85!?=
```

* Expected behavior

GMail decodes this as "Kviečiame drauge pildyti ESO pasižadėjimų girliandą!"

* Actual behavior

Mutt shows this as "Subject: Kviečiame drauge pildyti ESO pasižad��jimų girliandą!"

* Steps to reproduce

Edit some email in raw form and paste the Subject header from above, then open it in Mutt.

* Used program versions

NeoMutt 20171215

* Operating System and its version

Ubuntu 17.10.

**Comment by gahr** [comment] 2017-12-21 11:40
The issue is with the subject being broken into two lines in the middle of the `=C4=97` sequence. I'll look into that.

**Comment by gahr** [comment] 2017-12-21 12:36
`rfc2047_decode` calls into `rfc2047_decode_word` for every piece of RFC2047-encoded string it finds. In this case, `rfc2047_decode_word` is called twice:

1. the first call, with the whole subject as argument, decodes the first part of the subject
2. the second call, with only the second part as argument, decodes the second part of the subject

Also, part of `rfc2047_decode_word`'s job is to perform charset encoding. It is the one who finds out that the RFC2047 parts are encoded in UTF-8.

The problem is that the first part / second part of the subject ends / starts with an invalid UTF-8 sequence. The whole valid sequence is split between the two subject parts. This is what gets us the two invalid-sequence characters.

**Comment by gahr** [comment] 2017-12-21 12:46
As a side note, I see that both iOS Mail and Roundcube handle this subject just fine. However, I think this is strictly illegal in RFC2047 terms:

>  Each 'encoded-word' MUST represent an integral number of characters.
   A multi-octet character may not be split across adjacent 'encoded-
   word's.

**Comment by gahr** [comment] 2017-12-21 17:02
Marking this as an enhancement too, since this is about supporting MUAs violating RFC ;)

**Closed** 2018-01-20 17:04 UTC
Labels: bug:confirmed, status:ready, type:enhancement
