### ISSUE TITLE
Another segfault in SSL_write

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#1857] opened 2019-09-24 09:07 UTC
## Expected Behaviour

dunno

## Actual Behaviour

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f523f7aaa92 in ssl_write_internal () from /usr/lib64/libssl.so.1.1
(gdb) bt
#0  0x00007f523f7aaa92 in ssl_write_internal () from /usr/lib64/libssl.so.1.1
#1  0x00007f523f7aac91 in SSL_write () from /usr/lib64/libssl.so.1.1
#2  0x0000563d28498f61 in ssl_socket_write (conn=<optimized out>, buf=<optimized out>, count=<optimized out>) at conn/ssl.c:1403
#3  0x0000563d28496fce in mutt_socket_write_d (conn=0x563d2a3791b0, 
    buf=0x563d2a40d9d0 "a0000 STATUS \"Queue\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r\na0001 STATUS \"Drafts\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r\na0002 STATUS \"+INBOX\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES"..., len=549, dbg=dbg@entry=2) at conn/socket.c:162
#4  0x0000563d2848aa6e in cmd_start (adata=adata@entry=0x563d2a36e460, cmdstr=cmdstr@entry=0x563d284d226a "IDLE", flags=flags@entry=4 '\004') at imap/command.c:206
#5  0x0000563d2848aadb in imap_cmd_idle (adata=adata@entry=0x563d2a36e460) at imap/command.c:1361
#6  0x0000563d2848d3f1 in imap_check_mailbox (m=m@entry=0x563d2a368480, force=force@entry=false) at imap/imap.c:1201
#7  0x0000563d2848d595 in imap_mbox_check (m=0x563d2a368480, index_hint=<optimized out>) at imap/imap.c:2197
#8  0x0000563d2842f41b in mx_mbox_check (m=0x563d2a368480, index_hint=index_hint@entry=0x7ffe0c0421b4) at mx.c:1024
#9  0x0000563d2840db78 in mutt_index_menu () at index.c:1118
#10 0x0000563d284209c3 in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1243
```

If NeoMutt crashed, did your OS create a 'coredump' file?

yea

## Steps to Reproduce

dunno

## How often does this happen?

twice

## When did it start to happen?

recently, i didn't change anything except the auto-upgrade

## NeoMutt Version

```
NeoMutt 20180716-2513-1d5e12
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.2.14+ (x86_64)
ncurses: ncurses 6.1.20190609 (compiled with 6.1.20190609)
libidn: 1.35 (compiled with 1.35)
GPGme: 1.13.0
hcache backends: bdb

Compiler:
Using built-in specs.
COLLECT_GCC=x86_64-pc-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-8.3.0-r1/work/gcc-8.3.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.3.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 8.3.0-r1 p1.1' --enable-esp --enable-libstdcxx-time --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-libmpx --disable-systemtap --enable-vtable-verify --enable-lto --without-isl --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.3.0 (Gentoo Hardened 8.3.0-r1 p1.1) 

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --libdir=/usr/lib64 --disable-doc --enable-nls --disable-notmuch --enable-gpgme --enable-pgp --disable-smime --enable-bdb --disable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --enable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls

Compilation CFLAGS: -O2 -pipe -march=ivybridge -mtune=skylake -ftree-vectorize -Og -ggdb3 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +sasl -smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
gentoo
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
imap

**Comment by flatcap** [comment] 2019-10-29 11:35
I've just fixed a bug in the SSL code that might have been the cause of this bug.
952dc61fc - After a failed connection, some data was free, but a pointer was left dangling.
I think this explains the crash and the intermittent nature.

**Comment by l29ah** [comment] 2019-11-11 11:04
dunno lol
NeoMutt 20191111
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056330d1fe223 in ssl_socket_write (conn=0x56330e96ddf0, 
    buf=0x56330e9f8380 "a0000 STATUS \"+INBOX\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r\na0001 STATUS \"Junk\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r\na0002 STATUS \"Trash\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r"..., count=414) at conn/ssl.c:1404
1404	conn/ssl.c: No such file or directory.
(gdb) bt
#0  0x000056330d1fe223 in ssl_socket_write (conn=0x56330e96ddf0, 
    buf=0x56330e9f8380 "a0000 STATUS \"+INBOX\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r\na0001 STATUS \"Junk\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r\na0002 STATUS \"Trash\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r"..., count=414) at conn/ssl.c:1404
#1  0x000056330d1fc296 in mutt_socket_write_d (conn=0x56330e96ddf0, 
    buf=0x56330e9f8380 "a0000 STATUS \"+INBOX\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r\na0001 STATUS \"Junk\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r\na0002 STATUS \"Trash\" (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)\r"..., len=414, dbg=dbg@entry=2) at conn/socket.c:164
#2  0x000056330d1efc55 in cmd_start (adata=adata@entry=0x56330e96d930, cmdstr=cmdstr@entry=0x56330d2372aa "IDLE", flags=flags@entry=4 '\004') at imap/command.c:206
#3  0x000056330d1efcc2 in imap_cmd_idle (adata=adata@entry=0x56330e96d930) at imap/command.c:1362
#4  0x000056330d1f25f9 in imap_check_mailbox (m=m@entry=0x56330e9611c0, force=force@entry=false) at imap/imap.c:1202
#5  0x000056330d1f279d in imap_mbox_check (m=0x56330e9611c0, index_hint=<optimized out>) at imap/imap.c:2196
#6  0x000056330d193a69 in mx_mbox_check (m=0x56330e9611c0, index_hint=index_hint@entry=0x7fffe11cd324) at mx.c:1039
#7  0x000056330d171a6c in mutt_index_menu () at index.c:1152
#8  0x000056330d184cec in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1260
```

**Comment by flatcap** [comment] 2019-11-11 11:32
_sigh_.  Sorry, I'll keep looking.

**Comment by flatcap** [comment] 2019-11-15 11:43
I've pushed to [[devel/ssl]](https://github.com/neomutt/neomutt/tree/devel/ssl).
It'll stop the crash.  Whether or not the connection will be retried, I don't know.

Please can you give it a try.
Thanks.

**Comment by flatcap** [comment] 2019-11-18 12:02
Merged.  Please re-open when you get the next crash ;-)

**Closed by flatcap** 2019-11-18 12:02 UTC
Labels: bug:crash
