### ISSUE TITLE
neomutt doesn't cope with external modification of the maildir

### ISSUE THREAD

**Issue by bobek** [neomutt/neomutt#2212] opened 2020-03-26 10:40 UTC
## Expected Behaviour

My setup uses `offlineimap` for synchronization of the local maildirs with the remote server(s). Everything worked without issues until `20191207+dfsg.1-1.1` (I am on Debian sid). E.g. when emails removed on the remote server and then deleted by offlineimap, neomutt sees the change and cope with it nicely.

## Actual Behaviour

- neomutt will report something like "mailbox externally modified, flags can be wrong"
- it doesn't refreshes pager, so it still includes already removed email. When trying to interact with such email, I will just get `No such file or directory (errno = 2)`.

Only way how to "recover" is to exit neomutt with commiting changes (e.g. with `x`) and reopen the folder. Interestingly it will still correctly detect appearance of the new email.

## Steps to Reproduce

- open folder
- remove email/file from the folder outside of neomutt

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  I believe, that the previous version was 2019-11-11, where it was ok. Not 100% sure though.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.5.0-rc5-amd64 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-bCiSXv/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

I have tried playing with settings like 

```
set header_cache="~/.mutt_hcache/"
set header_cache_backend="tokyocabinet"
set maildir_check_cur=no
set maildir_header_cache_verify=yes
set message_cache_clean=yes
set read_inc=1000
```

but it has not changed the observed behavior.

Thank you very much for any ideas! And also appreciate your work.

**Comment by hsanson** [comment] 2020-04-06 12:02
This is already reported at #1975

**Comment by bobek** [comment] 2020-04-06 12:11
> This is already reported at #1975 

Thank you for the link. This suggests that the problem is with folder management / indexing as general. The mentioned ticket is solely talking about virtual folders. My report is really about physical maildirs.

**Comment by simonjbeaumont** [comment] 2020-04-08 07:22
I also have this issue. If I delete mail on my phone then it doesn't remove from my mutt index and actions within mutt complain that the item doesn't exist. Need to re-open mutt to have it remove the item from the index. Same setup as above (mbsync + mutt). Used to get a "Mailbox externally modified" message and things "just worked".

**Comment by simonjbeaumont** [comment] 2020-04-08 07:25
See also #2150

**Comment by gahr** [comment] 2020-04-23 08:12
Closing as duplicate of #2077

**Closed by gahr** 2020-04-23 08:12 UTC
