### ISSUE TITLE
My mailboxes cannot be sourced on release NeoMutt 2019-11-11

### ISSUE THREAD

**Issue by thecsw** [neomutt/neomutt#1958] opened 2019-11-11 23:55 UTC
## Expected Behaviour

I was trying to open my mailboxes through neomutt.

## Actual Behaviour

It couldn't source them, here is the output:

```
Unknown Mailbox: /home/thecsw/.mail/cto/
Error in /home/thecsw/.mutt/accounts/cto, line 2: 
Unknown Mailbox: /home/thecsw/.mail/cto/
Error in /home/thecsw/.mutt/accounts/cto, line 3: 
Unknown Mailbox: /home/thecsw/.mail/cto/
Error in /home/thecsw/.mutt/accounts/cto, line 4: 
Error in /home/thecsw/.muttrc, line 3: source: file /home/thecsw/.mutt/accounts/cto could not be sourced
Unknown Mailbox: /home/thecsw/.mail/personal/
Error in /home/thecsw/.mutt/accounts/personal, line 2: 
Unknown Mailbox: /home/thecsw/.mail/personal/
Error in /home/thecsw/.mutt/accounts/personal, line 3: 
Unknown Mailbox: /home/thecsw/.mail/personal/
Error in /home/thecsw/.mutt/accounts/personal, line 4: 
Error in /home/thecsw/.muttrc, line 4: source: file /home/thecsw/.mutt/accounts/personal could not be sourced
Unknown Mailbox: /home/thecsw/.mail/mymail/
Error in /home/thecsw/.mutt/accounts/mymail, line 2: 
Unknown Mailbox: /home/thecsw/.mail/mymail/
Error in /home/thecsw/.mutt/accounts/mymail, line 3: 
Unknown Mailbox: /home/thecsw/.mail/mymail/
Error in /home/thecsw/.mutt/accounts/mymail, line 4: 
Unknown Mailbox: /home/thecsw/.mail/mymail/
Error in /home/thecsw/.mutt/accounts/mymail, line 5: 
Error in /home/thecsw/.muttrc, line 5: source: file /home/thecsw/.mutt/accounts/mymail could not be sourced
source: errors in /home/thecsw/.muttrc
Press any key to continue...
```

If NeoMutt crashed, did your OS create a 'coredump' file? N/A

## Steps to Reproduce

Just upgrade to the new release. btw, I use arch and pacman downloaded the update. When I rebuilt and installed the previous release from neomutt repo, it worked fine. When I went back and built the new release, and installed it, it broke again.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?
  I was using NeoMutt 2019-11-02 and it was working fine

- When I changed my config
  Can you narrow down **what** you changed?

## NeoMutt Version

```
NeoMutt 20180716-2774-b39b9b
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.10-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)

Compiler:
cc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: 

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/usr/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss -hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch -openssl +pgp -sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version `Linux ctu 5.3.10-arch1-1 #1 SMP PREEMPT Sun, 10 Nov 2019 11:29:38 +0000 x86_64 GNU/Linux`
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local with offlineimap

**Comment by fbellet** [comment] 2019-11-12 09:12
Same here. It seems related to commit b7273ebc22.

**Comment by noctux** [comment] 2019-11-12 09:36
I got the same issue. The issue seems to be with hierachial mailboxes for me (as they happen when syncing my maildir++ to a local maildir using isync/mbsync in my case).

I have a mailbox command like this inside my config:

```
set mbox_type=Maildir
set folder=~/Mail/
mailboxes +/work +/work/INBOX +/work/projects +/work/projects/stuff +/work/projects/misc ...
```

However, after syncing not all are fully qualified maildir mailboxes (as the "umbrella" folders like `work` and `work/projects`  lack `new`, `cur` and `tmp` folders of their own):

```
$ find ~/Mail -type d
/home/noctux/Mail
/home/noctux/Mail/work
/home/noctux/Mail/work/INBOX
/home/noctux/Mail/work/INBOX/new
/home/noctux/Mail/work/INBOX/tmp
/home/noctux/Mail/work/INBOX/cur
/home/noctux/Mail/work/projects
/home/noctux/Mail/work/projects/stuff
/home/noctux/Mail/work/projects/stuff/new
/home/noctux/Mail/work/projects/stuff/tmp
/home/noctux/Mail/work/projects/stuff/cur
/home/noctux/Mail/work/projects/misc
/home/noctux/Mail/work/projects/misc/new
/home/noctux/Mail/work/projects/misc/tmp
/home/noctux/Mail/work/projects/misc/cur
...
```

When I correct the mailboxes to this, however the initial sourcing works:
```
mailboxes +/work/INBOX +/work/projects/stuff +/work/projects/misc ...
```

However, this is not a full substitute for what I had previously:
I'm using the sidebar patch with folder indent:

```
set sidebar_short_path=yes
set sidebar_folder_indent=yes
```

Unfortunately, due to the missing intermediate mailboxes the hierarchial structure is gone and all mailboxes are displayed as a flat list, without indents or prefixes.

**Comment by kflak** [comment] 2019-11-13 08:28
I have the same issue, preventing me from seeing the `sent` inbox in the sidebar. Creating the folders `cur`, `new` and `sent` in the top-level mailbox seems to solve the issue. Not an optimal solution, though... is there a way to avoid this kind of hack? Currently my muttrc contains these lines:

```
set folder = ~/.mail
mailboxes = +"INBOX" +"sent" +"drafts"
```
and the file structure looks like this:

```
.mail
├── cur
├── drafts
│   ├── cur
│   ├── new
│   └── tmp
├── INBOX
│   ├── cur
│   ├── new
│   └── tmp
├── new
├── sent
│   ├── cur
│   ├── new
│   └── tmp
├── Sent
│   ├── cur
│   ├── new
│   └── tmp
└── tmp
```

**Comment by Ornanovitch** [comment] 2019-11-14 14:46
Same here since upgrade to 2019.11.11

**Comment by doronbehar** [comment] 2019-11-15 09:50
Same here, very severe issue.. Once this will be fixed, we need to make sure commands like this work as well (for my use case):

```mutt
set my_current_account = $MUTT_ACCOUNT
set spoolfile = +$my_current_account"/INBOX"
```

**Comment by flatcap** [comment] 2019-11-15 11:07
Yes, the `mailboxes` command has become more strict.
See [my comment here](https://github.com/neomutt/neomutt/issues/1901#issuecomment-547676531) for a **workaround**.

@doronbehar 
This behaviour changed long before the 2019-11-02 release.
What problem are you experiencing?

**Comment by kflak** [comment] 2019-11-15 11:33
@flatcap 
Thanks for the link to your comment! I changed my muttrc from 
```
mailboxes = +"INBOX" +"sent"
```
to 
```
named-mailboxes "INBOX" =INBOX
named-mailboxes "Sent" =sent
```
and my sidebar is again pristine, as is my .mail/ folder that I kept the mailboxes in. No more dummy mailboxes : -D

**Comment by doronbehar** [comment] 2019-11-15 12:34
@kflak that's more useful, thanks. @flatcap I'm not sure I've figured out from that comment you linked how to use the `mailboxes` command in a mutt compatible manner. I'm not interested in account dividers..

**Comment by flatcap** [comment] 2019-11-15 12:42
@doronbehar 
If you `mailboxes` something, it **must** exist either as empty `file` (mbox) or empty `dir/{cur,new,tmp}` (maildir)
I don't understand your example.  Without a `$folder` it won't work.

**Comment by doronbehar** [comment] 2019-11-15 12:51
@flatcap all of my mailboxes have `{cur,new,tmp}` directories and I get an error for all of them.

**Comment by flatcap** [comment] 2019-11-15 13:03
Sorry, I don't know what's going on.
Can you check your logs for any clues.
Can you bisect to the commit that caused your problem?
Can you debug to see where the failure's happening?

**Comment by kflak** [comment] 2019-11-15 13:04
@doronbehar I thought I had the same, but then I realized that my toplevel mailbox (~/.mail) did not in fact have that. I did a `mkdir cur tmp new` in that dir, and the problem went away. However, this left an empty mailbox called ~/.mail/ at the top of my sidebar. When using the `named-mailboxes` this problem vanished. In context, the relevant `muttrc` lines are this: 
```
set folder = ~/.mail
set spoolfile = "+INBOX"        
named-mailboxes "INBOX" =INBOX
named-mailboxes "Sent" =sent
```
Not sure if that helps you, but it seems to do the trick for me.

**Comment by doronbehar** [comment] 2019-11-15 13:16
Thanks again @kflak ! This was it :sweat_smile:.

@flatcap so as part of the new architectural changes etc, was it intentional to check specifically if the `folder` is actually a maildir? I think many users with multiple accounts have a setup like me and @kflak and they set a folder with `mailboxes` that start with the prefix of the account.. To be more clear, I think specifically the `folder` shouldn't be checked, but I guess yea, the `mailboxes` should.

**Comment by hakova** [comment] 2019-11-16 19:43
Thank you for this very helpful thread. I was able to solve my problem using the information here.

**Comment by Ornanovitch** [comment] 2019-11-17 20:24
> ```
> set folder = ~/.mail
> set spoolfile = "+INBOX"        
> named-mailboxes "INBOX" =INBOX
> named-mailboxes "Sent" =sent
> ```

Wow, thank you @kflak and thank you @flatcap, this `named-mailboxes` feature is a major improvement ! :ok_hand: 
![2019-11-17-212102_269x304_escrotum](https://user-images.githubusercontent.com/34077099/69013474-a2cc8e00-0980-11ea-8d07-0689a3112ccb.png)

**Comment by thecsw** [comment] 2019-11-17 20:29
@Ornanovitch how did you make that GMAIL delimiter? By any chance you have your mutt config published?

**Comment by Ornanovitch** [comment] 2019-11-17 21:15
> By any chance you have your mutt config published?

Not yet but I plan to do that !

Here is my simple trick : 
```
set spoolfile = "+INBOX"
set record = ""
set postponed = "+[Gmail].Drafts"
set trash = "+[Gmail].Trash"
named-mailboxes "   Reçus" =INBOX
named-mailboxes "   Envoyés" ="[Gmail].Sent Mail"
named-mailboxes "   Brouillons" =[Gmail].Drafts
named-mailboxes " ﮊ  Junk" =[Gmail].Spam
named-mailboxes "   Poubelle" =[Gmail].Trash
named-mailboxes " ---------   GMAIL ----------" ="."
named-mailboxes "   FELINN" =FELINN
named-mailboxes "   Logement" =Logement
named-mailboxes "   Paperasse" =Paperasse
named-mailboxes "   Personnel" =Personnel
named-mailboxes "   Dev Varreau" ="Site"
named-mailboxes "   Nuits d'Été" ="Nuits d'été"
named-mailboxes "   Copains" ="Blablabla"

```

**Comment by thecsw** [comment] 2019-11-17 21:31
@Ornanovitch Simply beautiful! Thanks for sharing!
Also, I've been using mutt/neomutt for the past 2 years now, but it's my first time seeing notation like `[Gmail].Drafts`, does it access the directories inside or different mailboxes?

The way I have things set up, I have 3 different account connect to my neomutt, each account has a different file that I just source into my `~/.muttrc`

**Comment by tdehaeze** [comment] 2019-11-18 08:00
I think that in order to use `="."`, you need to create new, cur and tmp folders in your .mail folder.
This seems a little bit hacky to me.

@thecsw How did you succeed to have multiple delimiters ? Did you had to create multiple empty mailboxes?

**Comment by Ornanovitch** [comment] 2019-11-18 08:02
> Also, I've been using mutt/neomutt for the past 2 years now, but it's my first time seeing notation like `[Gmail].Drafts`, does it access the directories inside or different mailboxes?

This is a gmail specific syntax which I never understood. It does nothing special, just a classical mailbox directory in my case (I sync with mbsync)
 
> The way I have things set up, I have 3 different account connect to my neomutt, each account has a different file that I just source into my `~/.muttrc`

I have a similar setup, 4 different accout.muttrc that I source with key bindings so that I have only one account in my sidebar at the same time.

> _UPD_ What is the dot for the delimeter? `="."`, my neomutt doesn't like that and just doesn't show the named mailbox altogether

Since I created `new` / `cur` / `tmp` in each mail-account parent directories, it goes there and shows an empty mailbox without error if I accidentally enter into it. So if I sourced all my accounts at the same time, I guess I would do something like : 

```
named-mailboxes " ---------   Account 1 ----------" ="parent-folder-for-account1"
named-mailboxes " etc.
named-mailboxes " etc.
named-mailboxes " ---------   Account 2 ----------" ="parent-folder-for-account2"
etc.
```

> **UPD** It is gorgeous. I use [iosevka](https://typeof.net/Iosevka/), so I used some of the [available characters](https://typeof.net/Iosevka/specimen.html)
If you are interested, [NerdFont](https://github.com/ryanoasis/nerd-fonts) has a patch for Iosevka !

**Comment by kflak** [comment] 2019-11-18 14:22
@Ornanovitch Thanks for the beautiful sidebar! You have inspired me to whip out some font-awesome icons and keep my sidebar visible at last ;-)

**Comment by thecsw** [comment] 2019-11-18 16:18
@tdehaeze I just used some empty mailboxes that I don't use, like `Journal`
```
set spoolfile = +'INBOX'
set trash = +'Deleted Items'
set postponed = +'Drafts'
set record = +'Sent Items'
named-mailboxes "―――――― ♠ KU ――――――" =Journal
named-mailboxes "↓ Inbox" =INBOX
named-mailboxes "↑ Sent" ='Sent Items'
named-mailboxes "∇ Trash" ='Deleted Items'
named-mailboxes "∗ Junk" ='Junk Email'
named-mailboxes "∃ Drafts" ='Drafts'
```

**Comment by thecsw** [comment] 2019-11-18 16:25
@Ornanovitch Great stuff! Thanks, already patching my font. Did you every have trouble with sending email from different accounts? I remember back in the old day I could switch mailboxes from different accounts and when I pressed `m` to send mail, it would send it from the account of the open mailbox. But now, when I try to send mail, it always grabs the last account I initialized.

**Comment by Ornanovitch** [comment] 2019-11-18 20:27
> I could switch mailboxes from different accounts

I've never had this kind of issue... If I understand you well, you keep all your mailboxes in the sidebar regardless the account you sourced. I don't use a "global" sidebar (it's loaded differently with each account .muttrc), so I can't have this problem, but I feel like this is a "by design logic". But maybe your conf is more different than what I think..

I don't know if it can helps, but here is a brief summary of my process : 

I have an account A, which is sourced by default, and accounts B, C, D which I can source with key bindings. Each accounts has its own .muttrc which has its own `set from` and its own `set sendmail = "msmtp -a [account]"`. Basic and classical I guess... But I noticed that it prevents me to write mails from a wrong account.

**Comment by Ornanovitch** [comment] 2019-11-18 20:28
> @Ornanovitch Thanks for the beautiful sidebar! You have inspired me to whip out some font-awesome icons and keep my sidebar visible at last ;-)

I'm glad you like it ! Enjoy :)

**Comment by hakova** [comment] 2019-11-20 02:25
@Ornanovitch Thank you for sharing your settings. I have a silly question: I installed the nerdfonts and modified my settings using them but the special characters show like empty rectangles on the sidebar instead of icons. What am I missing?

**Comment by f00wl** [comment] 2019-11-20 17:25
> @Ornanovitch Great stuff! Thanks, already patching my font. Did you every have trouble with sending email from different accounts? I remember back in the old day I could switch mailboxes from different accounts and when I pressed `m` to send mail, it would send it from the account of the open mailbox. But now, when I try to send mail, it always grabs the last account I initialized.

`folder-hook` probably does what you are looking for:
```
folder-hook yourmailboxe 'set sendmail = "msmtp -a yourmsmtpaccount'"
```

**Comment by hakova** [comment] 2019-11-21 02:02
This may be a little off-topic but does anyone have trouble in purging deleted emails from the named-mailboxes, when you switch folders? In my case, there is an inconsistent behavior of neomutt not purging the deleted emails (marked deleted it is) from the folder when switching folders,  but sometimes it does this as expected.

**Comment by thecsw** [comment] 2019-11-21 02:15
@hakova Yes! That happens to me too. It's pretty inconsistent and I never know how to replicate it.

**Comment by hakova** [comment] 2019-11-21 21:43
Thank you @thecsw, I will open an issue about this then.

**Comment by zingyb** [comment] 2019-11-22 17:06
To return to the original issue, I'll try to sum up for @flatcap:

Since the 2019-11-11 release, it appears that cur, new, and tmp directories are expected to live in wherever the user has set the value of `folder`. 2019-11-02's release does not exhibit this behavior.

To illustrate, I sync my mail with `isync` at the location ~/.local/share/isync/me@example.com. I have the following lines in my config file:

```
set folder          = "~/.local/share/isync/me@example.com"
mailboxes           = "+Inbox"
```
On previous versions, NeoMutt would happily automatically open "+Inbox" on start. Since 2019-11-11, I am greeted with the following error:

```
Unknown Mailbox: /home/me/.local/share/isync/me@example.com/
```
Manually creating cur, tmp, and new directories at  /home/me/.local/share/isync/me@example.com/ will cease the errors, but I agree that this feels rather hackish.

Is there some other directive that is expected to be placed in the configuration file?

Thanks!

**Comment by doronbehar** [comment] 2019-11-29 10:35
BTW, TIL that the new config option `sidebar_non_empty_mailbox_only` can be of use for those of us who are improving our configs. See doc: https://neomutt.org/guide/reference.html#3-343-%C2%A0sidebar_non_empty_mailbox_only

**Comment by kajzersoze** [comment] 2019-11-30 10:14
Same thing on 2019-11-29
Can't upgrade because of this two versions now.
A lot of noise and off topic things here.
Back to the original problem, is there an actual fix for this that I'm missing or it's a work in progress ?

**Comment by flatcap** [comment] 2019-11-30 10:56
@kajzersoze 
> Same thing on 2019-11-29

What problem, exactly, are you having?
What error messages are you seeing?
Have you looked in the logs for more info? `neomutt -d5` and see `~/.neomuttdebug0`

**Comment by kajzersoze** [comment] 2019-11-30 11:30
Exactly what the title says and what OP described.

**Comment by flatcap** [comment] 2019-11-30 11:45
Right.  I already [commented on that](https://github.com/neomutt/neomutt/issues/1958#issuecomment-554318391).

The `mailboxes` command is stricter, now.

If that isn't your problem, then I need to see error messages and have a description of _how_ your problem is different.

**Comment by kajzersoze** [comment] 2019-11-30 12:20
Right, sorry, my bad, I missed that.
Everything is fine now.

**Comment by flatcap** [comment] 2019-11-30 12:23
> Right, sorry, my bad, I missed that.

No worries.

> Everything is fine now.

Great.

**Comment by gahr** [comment] 2019-12-09 12:00
I went through the discourse twice and I think everything that was raised has been discussed / solved. Closing this.

**Closed by gahr** 2019-12-09 12:00 UTC
