### ISSUE TITLE
sync-mailbox does not delete the correct message

### ISSUE THREAD

**Issue by Kdecherf** [neomutt/neomutt#2592] opened 2020-08-16 17:43 UTC
## Expected Behaviour

When I want to archive messages from `INBOX` maildir into a `Archive` maildir I press `y`.
The message is then marked as read/seen and saved into `Archive`.

Then I call `sync-mailbox` to mark for deletion and hide the message from `INBOX`.

Here is a `inotifywait -m` excerpt of the expected behavior:
```
# When I press 'y' to archive a message
.mail/kdecherf/Archive/tmp/ CREATE cur.<redacted>.sakura:2,S
.mail/kdecherf/Archive/tmp/ MODIFY cur.<redacted>.sakura:2,S
.mail/kdecherf/Archive/tmp/ MODIFY cur.<redacted>.sakura:2,S
.mail/kdecherf/Archive/tmp/ MODIFY cur.<redacted>.sakura:2,S
.mail/kdecherf/Archive/cur/ CREATE <redacted>.sakura:2,S
.mail/kdecherf/Archive/tmp/ DELETE cur.<redacted>.sakura:2,S

# When I press $ to sync-mailbox
.mail/kdecherf/INBOX/new/ MOVED_FROM <redacted>.sakura,U=38325:2,
.mail/kdecherf/INBOX/cur/ MOVED_TO <redacted>.sakura,U=38325:2,ST
```

## Actual Behaviour

When I call `sync-mailbox` neomutt marks for deletion the message in `Archive` instead of the one in `INBOX`, leading to an inconsistency in folders and messages randomly respawning later in the inbox.

Here is a `inotifywait -m` excerpt of the actual behavior:
```
# When I press 'y' to archive a message
.mail/kdecherf/Archive/tmp/ CREATE cur.<redacted>.sakura:2,S
.mail/kdecherf/Archive/tmp/ MODIFY cur.<redacted>.sakura:2,S
.mail/kdecherf/Archive/tmp/ MODIFY cur.<redacted>.sakura:2,S
.mail/kdecherf/Archive/tmp/ MODIFY cur.<redacted>.sakura:2,S
.mail/kdecherf/Archive/cur/ CREATE <redacted>.sakura:2,S
.mail/kdecherf/Archive/tmp/ DELETE cur.<redacted>.sakura:2,S

# When I press $ to sync-mailbox
.mail/kdecherf/Archive/cur/ MOVED_FROM <redacted>.sakura:2,S
.mail/kdecherf/Archive/cur/ MOVED_TO <redacted>.sakura:2,ST

```

## Steps to Reproduce

1. Archive a message
2. Call sync-mailbox
3. Check the corresponding files in the archive and inbox folders

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to `devel/maildir`

## NeoMutt Version

```
NeoMutt 20200814-9-91f6cf
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.48 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.14.0
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.2.0
storage: gdbm

Configure options: --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --prefix=/usr/x86_64-pc-linux-gnu --bindir=/usr/x86_64-pc-linux-gnu/bin --sbindir=/usr/x86_64-pc-linux-gnu/bin --libdir=/usr/x86_64-pc-linux-gnu/lib --datadir=/usr/share --docdir=/usr/share/doc/neomutt-20200814 --infodir=/usr/share/info --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --ssl --homespool --with-homespool=.maildir --with-lock=flock --gdbm --gpgme --disable-idn --idn2 --with-ui=ncurses --notmuch

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/x86_64-pc-linux-gnu/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set -fcntl +flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache +homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex -sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH=".maildir"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/bin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version 
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? maildir w/ notmuch and virtual mailboxes

The macro I use to archive messages:
```
folder-hook INBOX 'macro index,pager y "<enter-command>unset resolve<enter><clear-flag>N<enter-command>set resolve<enter><save-message><enter>" "Archive the message"'
```

A `git bisect` gives 8508ceebaa7e2ced78bc1330a71da43f0cba5b0a as the first offending commit.

**Comment by gahr** [comment] 2020-08-17 08:16
Duplicate of #2587 perhaps?

**Comment by Kdecherf** [comment] 2020-08-17 08:39
@gahr no, this issue is not a dup of #2587

**Closed** 2020-08-21 00:17 UTC
Labels: has:bisect, topic:notmuch, type:bug
