### ISSUE TITLE
sort-reverse by date disables sort=threads settings

### ISSUE THREAD

**Issue by vkuznet** [neomutt/neomutt#2719] opened 2020-10-30 16:50 UTC
I have the following settings in my configuration
```
set sort=threads
set sort_aux=reverse-last-date-received
```

But when I invoke sort-reverse action (via macro) and choose (d)ate option all mails are sorted according to date but I can't collapse threads and or anything with mail threads anymore. Instead I got a message:
*Threading is not enabled*

It seems to me that sort-reverse action disable my original sort settings and there is no way to come back to it.

I can invoke sort-reverse action and choose (t)hread option, it will sort mails by thread but their order changed to show oldest mails first and contradict my original settings to sort mails by last date first.

## Expected Behaviour

I would expect that after choice of sorting option I can come back to original settings

## Actual Behaviour
- after choosing sort option by date I can't longer collapse messages by threads
- after choosing sort option by thread the mails are ordered in asc order (older message first) which is opposite to my settings of desc order (last messages first)

## Steps to Reproduce

choose <sort-reverse> options

## How often does this happen?

- Always

## When did it start to happen?

I'm not sure

## NeoMutt Version

```
NeoMutt 20200925
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 19.6.0 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libiconv: 1.16
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.14.0-unknown
OpenSSL: OpenSSL 1.1.1h  22 Sep 2020
libnotmuch: 5.3.0

Configure options: --prefix=/opt/local --enable-doc --disable-idn --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local --with-zlib=/opt/local --with-gpgme=/opt/local --with-idn2=/opt/local --with-notmuch=/opt/local --with-sasl=/opt/local

Compilation CFLAGS: -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme -gss -hcache -homespool +idn -inotify
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl
  +smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/opt/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info
* Operating System and its version: macOS, 10.15.7
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local maildir

**Comment by gahr** [comment] 2020-11-02 11:57
I think what you are seeing is the intended behaviour. `sort-reverse` applies to `sort`, so if you sort-reverse by date you won't be sorting by threads anymore.

If you want a sorted view, you need to have `sort=threads` and play with `sort_aux` to get the sorting you want. You are not guaranteed to succeed in getting exactly the sorting you're looking for. There are some things that cannot be done. As an example, an attempt to "fix" a use case was suggested in #2433.

**Comment by gahr** [comment] 2020-11-05 16:07
Closing, this is working as designed.

**Comment by flatcap** [comment] 2020-11-05 16:26
Agreed.
Helping you would mean changing the behaviour of `<sort-mailbox>` and `<sort-reverse>`.
The alternative would be to add new functions `<sort-aux-mailbox>` and `<sort-aux-reverse>`.

---

However, I had a crazy idea how you might make this work (untested):
Create a macro `O` that:
- `<enter-command>set my_sort = $sort<enter>` # Save the original value
- `<sort-reverse>` # Call the original function
- `<enter-command>set sort_aux = $sort<enter>` # Transfer the value
- `<enter-command>set sort = $my_sort<enter>` # Restore the original value

Good luck!

**Closed by flatcap** 2020-11-05 16:26 UTC
Labels: closed:not-a-bug, type:question

**Comment by vkuznet** [comment] 2020-11-06 01:01
Guys, thanks for guidance and clarification. Finally, I made it works as I expect, here is my recipe:
- my original settings are
```
set sort=threads
set sort_aux=reverse-last-date-received
```
- I use `O` as sort-reverse where I can choose date if I want to or any other action
- then I added the following macro to comeback to my original settings after previous step
```
# reset original sort setting: sort by threads and sort_aux as reverse-last-date-received
macro index K \
    "<enter-command>set my_sort=threads<enter><sort-reverse>t<enter><change-folder>=Inbox<enter><enter-command>set sort_aux=reverse-last-date-received<enter><enter-command>set sort=threads<enter>"
```
and, voila, my settings are reset to original and I back  to my Inbox.

**Comment by flatcap** [comment] 2020-11-06 12:22
Great!  Glad you've got a solution :-)
