### ISSUE TITLE
sidebar_sort_method=alpha: does not sort mailboxes as expected

### ISSUE THREAD

**Issue by randomizedthinking** [neomutt/neomutt#739] opened 2017-08-30 23:42 UTC
* **bug reports**

    * Expected behavior
        * The sidebar_sort_method is stable and sorts the mailboxes alphabetically.
    * Actual behavior
        * The sidebar_sort_method=alpha does not sort mailboxes alphabetically. Furthermore, the order changes if I enter commands, such as `sidebar-prev` or `sidebar-next`. In my case, only mailbox 'Inbox' is affected. Not sure whether the internal logic is the same given the special mailbox folder. Please see the attached images.

![mutt-sidebar1](https://user-images.githubusercontent.com/5283430/29899598-414b9fb6-8da1-11e7-930d-0ef73e08c2da.png)

After `<down>` is pressed which is mapped to `sidebar-prev`.

![mutt-sidebar2](https://user-images.githubusercontent.com/5283430/29899599-4775b732-8da1-11e7-9c3b-e1b56297e407.png)

    * Used program versions
        * NeoMutt 20170113 (1.7.2)
    * Operating System and its version
        * Debian Stretch

**Comment by gahr** [comment] 2017-08-31 05:57
Inbox is supposed to go first. Can you post your `mailboxes` config?

**Comment by gahr** [comment] 2017-08-31 06:16
Oh, and your `sidebar_*` config too please

**Comment by randomizedthinking** [comment] 2017-08-31 16:36
Here are my settings for mailboxes and sidebar:

    mailboxes `find ~/.mail/hotmail -type d -name cur -printf '%h '`
    set sidebar_visible = yes
    set sidebar_width   = 40
    set sidebar_short_path = yes
    set sidebar_folder_indent = yes
    set sidebar_indent_string = "    "
    set sidebar_sort_method = alpha
    bind index,pager <down>   sidebar-next
    bind index,pager <up>     sidebar-prev
    bind index,pager <right>  sidebar-open

For the `mailboxes` setting, I have around 40 mailboxes and some of them are nested.

**Comment by gahr** [comment] 2017-09-01 08:04
For your use of `cur`, I understand that `~/.mail/hotmail` contains a maildir-style structure? If so, how does the `Inbox` come from? Do you have a folder explicitely named `Inbox`? It would be helpful to get the output of your `find` command.
Also, is `sidebar_delim_chars` set to the default `"/." `?

**Comment by randomizedthinking** [comment] 2017-09-01 15:59
Yes, there is a folder named `Inbox` explicitely. Also, the `sidebar_delim_chars` is set to the default value `"/."`.

**Comment by gahr** [comment] 2017-09-01 16:50
Thanks, I'll look into this. I fear that the inbox-first algo expects an initial hostname part in the path, to figure out which inbox belongs to which account. I'll have to think of a solution..

**Comment by randomizedthinking** [comment] 2017-09-02 05:41
Thanks, gahr! Also, I noticed another issue with the sidebar: when both `mailboxes` and `virtual-mailboxes` are set, the sidebar would show both. One has to run `<sidebar-toggle-virtual>` to alternate between mailboxes and virtual-mailboxes.

**Comment by gahr** [comment] 2017-09-02 08:28
Please open a separate issue for handling virtual mailboxes, of which I know next to nothing ;)

**Comment by gahr** [comment] 2017-09-07 11:51
I wasn't able to reproduce using the following setup:


```sh
% cat ~/neomutt-test/issue-739/cfg                                                                                                                       
mailboxes `find ~/neomutt-test/issue-739/hotmail -type d -name cur | xargs dirname | xargs`

set folder = "~/neomutt-test/issue-739/hotmail"
set sidebar_visible = yes
set sidebar_width = 40
set sidebar_short_path = yes
set sidebar_folder_indent = yes
set sidebar_indent_string = "   "
set sidebar_sort_method = alpha
set sidebar_delim_chars = "/"
```

```sh
% find ~/neomutt-test/issue-739/hotmail
/home/gahr/neomutt-test/issue-739/hotmail
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/cur
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/d-deals
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/d-deals/cur
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/m-mileage
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/m-mileage/cur
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/r-records
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/r-records/cur
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/a-account
/home/gahr/neomutt-test/issue-739/hotmail/05-shopping/a-account/cur
/home/gahr/neomutt-test/issue-739/hotmail/06-info
/home/gahr/neomutt-test/issue-739/hotmail/06-info/cur
/home/gahr/neomutt-test/issue-739/hotmail/06-info/a-accounts
/home/gahr/neomutt-test/issue-739/hotmail/06-info/a-accounts/cur
/home/gahr/neomutt-test/issue-739/hotmail/Inbox
/home/gahr/neomutt-test/issue-739/hotmail/Inbox/cur
/home/gahr/neomutt-test/issue-739/hotmail/Drafts
/home/gahr/neomutt-test/issue-739/hotmail/Drafts/cur
```
The output is

```
Inbox
05-shopping
   a-account
   d-deals
   m-mileage
   r-records
06-info
   a-accounts
Drafts
```

* what's your `folder` setting?
* what's the output of the `find` command you use in `mailboxes`?

**Comment by randomizedthinking** [comment] 2017-09-07 16:51
1. The `folder` setting is `~/.mail/hotmail`.

2. The output of the `find` command is a long string: /home/opensrc/.mail/hotmail/Inbox /home/opensrc/.mail/hotmail/Drafts /home/opensrc/.mail/hotmail/Sent /home/opensrc/.mail/hotmail/Trash /home/opensrc/.mail/hotmail/Junk /home/opensrc/.mail/hotmail/05-shopping /home/opensrc/.mail/hotmail/05-shopping/d-deals /home/opensrc/.mail/hotmail/05-shopping/r-records /home/opensrc/.mail/hotmail/05-shopping/m-mileage

I am using the default version shipped with Debian Stretch. Would it be an issue
to you?

**Comment by gahr** [comment] 2017-09-07 17:18
I don't see anything wrong in your conf. Perhaps 20170113 is a bit old. A few bugs related to the inbox-first functionality have been fixed since then. #489 comes to mind. Can you try a newer version?

**Comment by gahr** [comment] 2017-09-08 14:18
I could reproduce with neomutt-20170113. Closing this, as it's been fixed in the meanwhile.

**Closed by gahr** 2017-09-08 14:18 UTC
