### ISSUE TITLE
Data loss when deleting "duplicate" messages

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#2285] opened 2020-04-22 08:52 UTC
What I did:

- sent an email to vim_use@googlegroups.com
- wanted to send another email and wanted to double-check what I wrote
- ran offlineimap to see if my email made it to the list already (it hadn't)
- I opened a second instance of mutt with =sent-mail
- started writing another email in the first mutt
- in the second mutt noticed that the message is shown twice, with the duplicate symbol next to the second row, so I deleted the duplicate
- finished the other email in the first mutt and sent it
- got a weird timeout while signing error (probably unrelated), sent it again
- saw the second message duplicated in the second mutt that had =sent-mail open
- marked the second message for deletion too
- quit the second mutt, confirmed the deletion of the messages
- ran offlineimap again, saw the second message made it to the list, didn't see the first message
- opened mutt -f =sent-mail again to see if I sent it to the right address

## Expected Behaviour

- I expected to see one copy of each of the two new messages I sent today

## Actual Behaviour

- both messages were gone entirely!

## Steps to Reproduce

I haven't tried to reproduce this  yet.  It seems serious enough to report at once, without waiting to see if I can reproduce.

## How often does this happen?

- Even once is too many times!

(Luckily my offlineimap process involves committing my local ~/Mail into git, and luckily I ran offlineimap at the right time to capture the message that was deleted, so I can restore it from my git history.)

## When did it start to happen?

- This is the first time I noticed this particular problem

## NeoMutt Version

```
NeoMutt 20200320
Copyright (C) 1996-2016 Michael R. Elkins ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 5.3.0-46-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.12.0
GnuTLS: 3.6.9
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --tokyocabinet --full-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Įprastos parinktys:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Kompiliavimo parinktys:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua -lz4 +meta +mixmaster +nls +notmuch -openssl +pgp +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Ubuntu 19.10
* Were you using multiple copies of NeoMutt at once? yes
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local

**Comment by gahr** [comment] 2020-04-23 07:13
Is this a variation of #2212 perhaps?

**Comment by mgedmin** [comment] 2020-04-23 08:07
Could be!

Would offlineimap modify anything in a local maildir, when copying a new email from a local folder to the remote IMAP server?  I mean rename the email to add flags or something?

*checks git history*

looks like it does!  I see a bunch of commits like

```
diff --git a/sent-mail/cur/1579506162.R5502005636548870888.blynas:2,S b/sent-mail/cur/1579506587_0.26375.blynas,U=9956,FMD5=db57f729bd45c551450392180ed75146:2,S
similarity index 100%
rename from sent-mail/cur/1579506162.R5502005636548870888.blynas:2,S
rename to sent-mail/cur/1579506587_0.26375.blynas,U=9956,FMD5=db57f729bd45c551450392180ed75146:2,S
```

So, yes, if neomutt doesn't remove externally deleted messages from the display, that would account for it.

**Comment by gahr** [comment] 2020-04-23 08:10
Thanks for the investigation :) What do you suggest?

**Comment by gahr** [comment] 2020-04-23 08:12
Closing as duplicate of #2077 - we can continue the discussion over there

**Closed by gahr** 2020-04-23 08:12 UTC
