### ISSUE TITLE
Maildir creation fails (errno=21)

### ISSUE THREAD

**Issue by jwynn6** [neomutt/neomutt#551] opened 2017-04-26 16:05 UTC
When trying to save a message to a non-existent maildir  the interface prompts to create a new directory and then when yes is selected, it errors with an errno=21, indicating the directory already exists.  Which it does not. 

NeoMutt 20170421 (1.8.2)
System: Linux 4.10.6-1-ARCH (x86_64)
libidn: 1.33 (compiled with 1.33)
hcache backends: gdbm

**Comment by flatcap** [comment] 2017-04-27 11:58
Hmm... it works for me.
```
# muttrc
set mbox_type = maildir
```
Docs for [`$mbox_type`](https://www.neomutt.org/guide/reference#mbox-type)

I tried:
- <kbd>s</kbd> `=new-dir`
- <kbd>s</kbd> `=new-dir/`
- <kbd>s</kbd> `/path/to/new-dir`
- <kbd>s</kbd> `/path/to/new-dir/`

If `mbox_type` is set to its default `mbox`, then I can repeat your problem by specifying a non-existent dir with a trailing slash:

- <kbd>s</kbd> `=new-dir/`
> /home/user/mail/new-dir/: Is a directory (errno = 21)

**Comment by christopher-john-czettel** [comment] 2017-06-19 02:21
@jwynn6 I was able to reproduce your problem (with `$mbox_type` set to maildir as well as mbox):

 <kbd>s</kbd> `=new-dir/subdir`

erroneously reports `/home/user/mail/new-dir/subdir: Is a directory (errno = 21)`
even though it not exists. 

It seems the code that should create the actual dir in `mutt_save_confirm()` was missing. I have hopefully fixed this with commit 5cc4bfc. 

Please be so kind, check if everything now works as expected and let me know.

@flatcap: You actually found another bug - gratz! ;-)

 <kbd>s</kbd> `=new-dir/` 

The `"/home/user/mail/new-dir/: Is a directory (errno = 21)` error occurs when $mbox_type is set to `MUTT_MBOX` as this save call needs a filename and not a directory name (opposed to `MUTT_MAILDIR`).

The error message should be more user friendly like "is a directory, need a filename for mbox", so I also committed e1db65ec.

**Closed** 2017-06-24 10:31 UTC
Labels: bug:confirmed, has:patch, type:bug
