### ISSUE TITLE
Hitting any key after sending an e-mail acts as "Reply to all"

### ISSUE THREAD

**Issue by arekfu** [neomutt/neomutt#3061] opened 2021-10-08 08:39 UTC
## Steps to Reproduce

1. Open (`Enter`) an e-mail in the pager. I think the bug only appears when replying to a message that is not the root of a thread.
2. Reply to all (`g` for me). Write an e-mail with `vim`, and send it off via SMTP (`y` for me).
3. Neomutt goes back to the pager. I hit `q` to close the pager.

## Expected Behaviour

Neomutt should close the pager when I hit `q`.

## Actual Behaviour

Neomutt fires up `vim` again, as if I had hit `g`.

The bug does not seem to be specific to `q`. I once triggered it by hitting an arrow key.

## How often does this happen?

It happens consistently, but not on all messages. I think it does **not** happen on messages that are the root message of a thread.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-81-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-WmwApX/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* OS: Ubuntu 20.04
* I was not using multiple copies of `neomutt` at once
* Bug seen under `tmux`
* I use a local maildir with `notmuch` integration.

I have a level 2 debug log. I am attaching the relevant part (10:27:05 is when I hit `y` to send off the message; 10:27:14 is when I hit `q`).
[neomuttdebug0.log](https://github.com/neomutt/neomutt/files/7309742/neomuttdebug0.log)

**Comment by rionda** [comment] 2021-11-09 22:22
I definitively observed this behavior in the past (I also use vim, but I doubt it has anything to do with it).
I just updated to 20211029, so I need to check if it still happens.

**Comment by rionda** [comment] 2021-11-10 14:26
I don't observe this bug anymore.

**Comment by jindraj** [comment] 2021-11-10 16:48
I think I don't observe the bug also. It seems this issue is a duplicate of #2091. I'm mentioning it here so both could be closed at once.

**Comment by arekfu** [comment] 2021-11-15 08:53
I can confirm that I am not seeing the bug anymore in 20211029.

**Comment by rionda** [comment] 2021-11-15 13:02
@flatcap : seems like this one can be closed.

**Closed** 2023-12-22 08:07 UTC
Labels: type:bug
