### ISSUE TITLE
Email signature not always attaching.

### ISSUE THREAD

**Issue by ethancedwards8** [neomutt/neomutt#2694] opened 2020-10-10 00:15 UTC
I have a signature in my mutt config directory, and have `set signature="./signature" in my muttrc, but it doesn't always attach when sending an email or replying

## Expected Behaviour

Have my signature auto attach

## Actual Behaviour

It doesn't attach at all

## If NeoMutt crashed, did your OS create a 'coredump' file?

N/A

## Steps to Reproduce

Use mutt-wizard from Luke Smith, add the line I have above and create a signature file

## How often does this happen?

- Sometimes

## When did it start to happen?

I'm not sure

## NeoMutt Version

20200925?

```
NeoMutt 20200925
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.8.13-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.14.0
GnuTLS: 3.6.15
libnotmuch: 5.3.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

I'm using Mutt Wizard from Luke Smith

* Operating System and its version Arch Linux
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? tmux but the issue still occurs without it
* Is your email local (maildir) or remote (IMAP)? synced to my machine using imapsync

**Comment by gahr** [comment] 2020-10-13 14:03
Does it help if you set it to an absolute path? Were you navigating (attachments, different mailboxes, ...) when it wasn't attaching?

**Comment by ethancedwards8** [comment] 2020-10-13 20:31
It does, actually! I set it to use the full path and it now always attaches. Thanks for the help. 

Not sure if this is a bug or user error to be honest. I thought the path was relative to the muttrc file.

**Comment by gahr** [comment] 2020-10-13 21:01
I think the issue is that the signaure path is resolved when the signature is read, and not at startup. Does your works vs. does not work scenarios depend on the directory you are in when you launch NeoMutt or does it stop/resume working during a single session?

**Comment by jindraj** [comment] 2020-10-13 21:09
I agree with gahr. @ethancedwards8 can you please try it with current master? Since yesterday there's a added error message when there's a problem with attaching signature file cfa1ef3642232de4c0566a48bcde0c224ecc88bf
If there's a problem with attaching signature file You should have been able to see full path of the file with some descriptive error.

**Comment by ethancedwards8** [comment] 2020-10-14 00:32
> I think the issue is that the signaure path is resolved when the signature is read, and not at startup. Does your works vs. does not work scenarios depend on the directory you are in when you launch NeoMutt or does it stop/resume working during a single session?

it worked when I was in my mutt config directory. I think it's relative to when you start mutt. @gahr

**Comment by ethancedwards8** [comment] 2020-10-14 00:36
> I agree with gahr. @ethancedwards8 can you please try it with current master? Since yesterday there's a added error message when there's a problem with attaching signature file [cfa1ef3](https://github.com/neomutt/neomutt/commit/cfa1ef3642232de4c0566a48bcde0c224ecc88bf)
> If there's a problem with attaching signature file You should have been able to see full path of the file with some descriptive error.
```
./signature: No such file or directory (errno = 2)
``` Yup, I don't get this error when providing the full path to the signature file

**Comment by gahr** [comment] 2020-10-14 08:08
> > I think the issue is that the signaure path is resolved when the signature is read, and not at startup. Does your works vs. does not work scenarios depend on the directory you are in when you launch NeoMutt or does it stop/resume working during a single session?
> 
> it worked when I was in my mutt config directory. I think it's relative to when you start mutt. @gahr

Yup, then I think PEBKAC - I'll close this. :)

**Closed by gahr** 2020-10-14 08:08 UTC
Labels: type:bug
