### ISSUE TITLE
Folder hooks not work with virtual mailboxes.

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#1125] opened 2018-04-04 10:19 UTC
## bug reports

* Expected behavior
When changing to a virtual mailbox all hooks defined to that mailbox should be executed.

* Actual behavior
Folder hooks seem to have no effect on virtual mailboxes.

* Steps to reproduce
Set some virtual mailboxes and hooks:

    virtual-mailboxes "Inbox"   "notmuch://?query=tag:inbox AND NOT tag:deleted
    virtual-mailboxes "Trash"   "notmuch://?query=tag:deleted

    folder-hook Inbox 'macro index,pager d <modify-labels>+deleted<enter>'
    folder-hook Trash 'macro index,pager i <modify-labels>-deleted<enter>'

See that the macros are never set when changing to the virtual mailboxes.

Another example is the classic method to collapse read threads when opening a mailbox:
    
    unset collapse_unread
    folder-hook . 'push <collapse-all>'

This works when jumping between mailboxes but does nothing when jumping between virtual mailboxes.

* Used program versions

```
NeoMutt 20180323-56-92914f
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.13.0-37-generic (x86_64)
ncurses: ncurses 6.0.20160213 (compiled with 6.0.20160213)
libidn: 1.32 (compiled with 1.32)
hcache backends: lmdb

Compiler:
cc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --notmuch --lmdb --ssl --sasl --gpgme

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

コンパイル時オプション:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme -gss +hcache -homespool +idn -locales_hack -lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://www.neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by Austin-Ray** [comment] 2018-10-09 21:50
@hsanson @tbabej @dammmn 

can you verify that this issue still occurs for you? I have been unable to reproduce the issue with my current build.

**Comment by tbabej** [comment] 2018-10-09 22:51
Not working for me on `neomutt-20180716`.

The following is minimal version of neomuttrc I tested on:
```
# This variable specifies notmuch query type, supported types: 'threads' and
# 'messages'.
set nm_query_type = threads

# virtual-mailboxes description notmuch-URI { description notmuch-URI ...}
virtual-mailboxes "Personal"   "notmuch://?query=(tag:gmail or tag:pmail) AND tag:inbox"
virtual-mailboxes "PQ"         "notmuch://?query=tag:pqmail AND tag:inbox"  # PQ INBOX

# Whitelist the grouping folders
sidebar_whitelist Personal
sidebar_whitelist PQ

# Set account stuff when entering the folder
folder-hook PQ       "source ~/.dotfiles/muttrc.d/account.pq"
folder-hook Personal "source ~/.dotfiles/muttrc.d/account.protonmail"

macro index <f2> '<enter-command>source ~/.dotfiles/muttrc.d/account.protonmail<enter>'
macro index <f3> '<enter-command>source ~/.dotfiles/muttrc.d/account.pq<enter>'
```

**Comment by Austin-Ray** [comment] 2018-10-10 01:08
@tbabej thank you for getting back to me so quickly!

I think I have found the root of the problem! 

`folder-hook` executes the regex on the path to a mailbox. For a normal mailbox, you don't get to set a name so the name and path are the same. A `folder-hook` for a `virtual-mailboxes` declaration needs to match on the query portion, not the name. 

For example:
```vim
virtual-mailboxes "WRONG" "notmuch://?query=tag:inbox"
folder-hook inbox 'set nm_query_type=threads"
```
Works because `inbox` is in the path (query.)

So `folder-hook` works the same on a `virtual-mailboxes` declaration as a `mailboxes` declaration. However, its usage is not intuitive and the documentation does not explicitly address using `folder-hooks` on `virtual-mailboxes`[0][1]. Furthermore, since `notmuch` queries are much more complex than regular mailbox paths, it is harder to construct regexes to affect a specific mailbox.

Until a patch is introduced to regex match the name, please regex match the query. There are some caveats regarding mailbox matching. Please reference the documentation[1]. I have found that lowercase regexes are case-insensitive.

[0] https://neomutt.org/guide/configuration.html#7-%C2%A0setting-variables-based-upon-mailbox
[1] https://neomutt.org/guide/advancedusage.html#mailbox-hook

**Comment by tbabej** [comment] 2018-10-10 01:56
@Austin-Ray Great! I can confirm that this works. Thanks a bunch!

For anybody wondering how to match their complicated notmuch queries, here's the trick I used.

Convert a virtual mailbox:

    virtual-mailboxes "Personal"  "notmuch://?query=<your-query>"

into

    virtual-mailboxes "Personal"  "notmuch://?query=tag:_email1 OR (<your-query>)"

and then use

    folder-hook _email1 "source ~/.dotfiles/muttrc.d/account.email1"

where `_email1` is a non-existing tag that simply serves as the identifier of that particular folder to match by the folder hook.

**Comment by Austin-Ray** [comment] 2018-10-10 21:40
The ergonomics of `folder-hook`s on `virtual-mailboxes` leave a lot to be desired, but do work so I'm closing this issues. The ergonomics issues are on the radar and will be fixed in the future.

**Closed by Austin-Ray** 2018-10-10 21:40 UTC
Labels: topic:notmuch

**Comment by Austin-Ray** [comment] 2019-01-04 02:41
@hsanson @tbabej @dammmn If any of you would like to test `folder-hook`s that can match on the description portion of a `virtual-mailboxes` declaration, I just opened #1521. It should be a proper resolution to this issue.
