### ISSUE TITLE
notmuch: obsolete interface

### ISSUE THREAD

**Issue by 0-wiz-0** [neomutt/neomutt#746] opened 2017-09-08 14:53 UTC
While testing the autosetup branch, I noticed the following compilation warnings:

````
mutt_notmuch.o mutt_notmuch.c
mutt_notmuch.c: In function ‘progress_update’:
mutt_notmuch.c:1130:5: warning: ‘notmuch_query_count_messages_st’ is deprecated: function deprecated as of libnotmuch 5.0 [-Wdeprecated-declarations]
     if (notmuch_query_count_messages_st(q, &count) != NOTMUCH_STATUS_SUCCESS)
     ^
In file included from mutt_notmuch.c:42:0:
/usr/pkg/include/notmuch.h:1042:1: note: declared here
 notmuch_query_count_messages_st (notmuch_query_t *query, unsigned int *count);
 ^
mutt_notmuch.c: In function ‘read_mesgs_query’:
mutt_notmuch.c:1317:3: warning: ‘notmuch_query_search_messages_st’ is deprecated: function deprecated as of libnotmuch 5.0 [-Wdeprecated-declarations]
   if (notmuch_query_search_messages_st(q, &msgs) != NOTMUCH_STATUS_SUCCESS)
   ^
In file included from mutt_notmuch.c:42:0:
/usr/pkg/include/notmuch.h:946:1: note: declared here
 notmuch_query_search_messages_st (notmuch_query_t *query,
 ^
mutt_notmuch.c: In function ‘read_threads_query’:
mutt_notmuch.c:1347:3: warning: ‘notmuch_query_search_threads_st’ is deprecated: function deprecated as of libnotmuch 5.0 [-Wdeprecated-declarations]
   if (notmuch_query_search_threads_st(q, &threads) != NOTMUCH_STATUS_SUCCESS)
   ^
In file included from mutt_notmuch.c:42:0:
/usr/pkg/include/notmuch.h:890:1: note: declared here
 notmuch_query_search_threads_st (notmuch_query_t *query, notmuch_threads_t **out);
 ^
mutt_notmuch.c: In function ‘count_query’:
mutt_notmuch.c:1708:5: warning: ‘notmuch_query_count_messages_st’ is deprecated: function deprecated as of libnotmuch 5.0 [-Wdeprecated-declarations]
     if (notmuch_query_count_messages_st(q, &res) != NOTMUCH_STATUS_SUCCESS)
     ^
In file included from mutt_notmuch.c:42:0:
/usr/pkg/include/notmuch.h:1042:1: note: declared here
 notmuch_query_count_messages_st (notmuch_query_t *query, unsigned int *count);
 ^
mutt_notmuch.c: In function ‘nm_message_is_still_queried’:
mutt_notmuch.c:2021:7: warning: ‘notmuch_query_search_messages_st’ is deprecated: function deprecated as of libnotmuch 5.0 [-Wdeprecated-declarations]
       if (notmuch_query_search_messages_st(q, &messages) != NOTMUCH_STATUS_SUCCESS)
       ^
In file included from mutt_notmuch.c:42:0:
/usr/pkg/include/notmuch.h:946:1: note: declared here
 notmuch_query_search_messages_st (notmuch_query_t *query,
 ^
mutt_notmuch.c:2034:7: warning: ‘notmuch_query_search_threads_st’ is deprecated: function deprecated as of libnotmuch 5.0 [-Wdeprecated-declarations]
       if (notmuch_query_search_threads_st(q, &threads) != NOTMUCH_STATUS_SUCCESS)
       ^
In file included from mutt_notmuch.c:42:0:
/usr/pkg/include/notmuch.h:890:1: note: declared here
 notmuch_query_search_threads_st (notmuch_query_t *query, notmuch_threads_t **out);
 ^
mutt_notmuch.c: In function ‘nm_check_mailbox’:
mutt_notmuch.c:2406:3: warning: ‘notmuch_query_search_messages_st’ is deprecated: function deprecated as of libnotmuch 5.0 [-Wdeprecated-declarations]
   if (notmuch_query_search_messages_st(q, &msgs) != NOTMUCH_STATUS_SUCCESS)
   ^
In file included from mutt_notmuch.c:42:0:
/usr/pkg/include/notmuch.h:946:1: note: declared here
 notmuch_query_search_messages_st (notmuch_query_t *query,
 ^
````
That's with notmuch-0.25 installed, in case it matters.

**Comment by yourealwaysbe** [comment] 2017-09-11 12:34
I am also on notmuch-0.25 and calling vfolder-from-query causes a segmentation fault.

This is with neomutt.20170907.r3.g659cd2dc-1 installed via the Arch AUR neomutt-git package.

**Comment by flatcap** [comment] 2017-09-11 14:12
I've change the code to use the v5 API -- branch [[devel/notmuch5](https://github.com/neomutt/neomutt/tree/devel/notmuch5)]
It doesn't crash when I do a few simple queries (but I'm not a notmuch user).
Please can you give it a try.

**Comment by yourealwaysbe** [comment] 2017-09-11 22:55
Thanks for looking into this.  It still crashes for me unfortunately.  This is NeoMutt 20170907-4-e32560 (1.9.0).  I tried -d 5, -d 2, and compiling with -g and using valgrind, but didn't find anything useful to help you find the error.  I just get

    Invalid read of size 4 at 0x1EC45B: ??? (in /usr/bin/mutt)

which i hoped -g would make more descriptive.

**Comment by flatcap** [comment] 2017-09-12 00:06
@yourealwaysbe OK, thanks.
I've found and fixed a problem with `vfolder-from-query`
Hopefully this should fix your crash.

@flokli Please can you take a look at my fix: fcd6bd7
I've changed the `query_type_to_string()` calls to use `0` and let it decide on a default ("messages").

**Comment by flokli** [comment] 2017-09-12 05:36
Urgh - somehow I didn't get this issue report - will need to check!

I also saw the deprecation warnings, seems like it still uses the old API - I'll need to take a look into that - still shouldn't segfault.

@yourealwaysbe Can you send the query you executed which caused it to crash? Did simple queries work? Did you set any defaults in your config?

@flatcap I'll take a look at fcd6bd7 in some hours, but being able to reproduce would help anyways ;-)

**Comment by yourealwaysbe** [comment] 2017-09-12 06:57
Just some quick info: f61124a1aa25a9d5bf1e0dbad2be2a4869776e6b seems to be the commit that breaks things for me. f2beb53f8265d51e74ddc72f517189c6e5bdc564 works fine.

@flatcap thanks for the fix -- i will test it sometime today (i have to dash out now)

@flokli it is all queries that fail (or at least i tried many but couldn't find one that didn't fail)

**Comment by flokli** [comment] 2017-09-12 08:56
@yourealwaysbe Did you set `nm_query_type` in your config? Does it only happen with hand-crafted queries, or also with the virtual folder listing?

**Comment by yourealwaysbe** [comment] 2017-09-12 09:16
@flatcap NeoMutt 20170907-5-fcd6bd (1.9.0) works for me.  Many thanks for the super fast fix

@flokli Perhaps this is fixed now, but for info, this is the only notmuch config i have: 

    set nm_default_uri = "notmuch:///home/matt/.config/mutt/mail"
    bind index,pager Q vfolder-from-query
    folder-hook $nm_default_uri. 'exec toggle-write'

I don't usually use virtual folders otherwise.  However, when testing, it looks like hand-crafter queries do not crash *if* i have used change-vfolder before in the same session.

**Comment by flokli** [comment] 2017-09-12 12:19
@yourealwaysbe Please check if 60856ba1f00e4ab54ddb1f67787db6d2b0bb4636 works for you too.

**Comment by yourealwaysbe** [comment] 2017-09-12 12:27
@flokli 60856ba1f00e4ab54ddb1f67787db6d2b0bb4636 also works.  Thanks.

**Comment by flatcap** [comment] 2017-09-12 13:21
Fixed in:
1bf3d02 fix: crash in vfolder-from-query
c8dcb09 notmuch: add support for the v5 API

**Closed by flatcap** 2017-09-12 13:21 UTC
Labels: bug:crash, status:new-bug, topic:notmuch, type:bug
