### ISSUE TITLE
libreoffice odt file not open with proper application

### ISSUE THREAD

**Issue by sassmann** [neomutt/neomutt#556] opened 2017-04-28 09:04 UTC
As a test create a file with libreoffice writer, save it, add it as attachment to a new mail.
The file is recognized as application/octet-stream.
`  A     2 /dev/shm/test.odt              [applica/octet-stre, base64, 7,8K]`
in .muttrc I have set
`mime_lookup application/octet-stream application/X-Lotus-Manuscript`
so that application/octet-stream should be looked up via /etc/mime.types instead of mailcap.
Also note what xdg-mime says about the file
```
xdg-mime query filetype /dev/shm/test.odt
application/vnd.oasis.opendocument.text
```
From /etc/mime.types
application/vnd.oasis.opendocument.text                         odt

Back in mutt, when trying to view the attachment while editing new mail it is shown in plaintext giving the error "No matching mailcap entry found.  Viewing as text."

Expected result: Open the document with libreoffice
Version: NeoMutt 20170421 (1.8.2)

**Comment by christopher-john-czettel** [comment] 2017-06-16 23:12
# REPLICATION

I tried to replicate your problem with my debian stretch default neomutt (NeoMutt 20170113 (1.7.2)) and config - no luck.

After that I built NeoMutt 20170421 (1.8.2) directly from the git source. (`./prepare; make`) and was able to reproduce your bug (even without the `mime_lookup` option running `./mutt -nF /dev/null -d 9`). I noticed that the mime-type was already set incorrectly to `application/octet-stream` whilst the attaching process.

# ANALYSIS

A short attached strace unveiled the problem:

```
...
rt_sigaction(SIGINT, {sa_handler=0x56436798a110, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fd11f9f2030}, NULL, 8) = 0 
open("/home/chris/.mime.types", O_RDONLY) = **-1 ENOENT (No such file or directory)**
open("/usr/local/etc/mime.types", O_RDONLY) = **-1 ENOENT (No such file or directory)**
open("/usr/local/share/mutt/mime.types", O_RDONLY) = **-1 ENOENT (No such file or directory)**
stat("/home/chris/mutt.odt", {st_mode=S_IFREG|0640, st_size=7998, ...}) = 0 
open("/home/chris/mutt.odt", O_RDONLY)  = 4    
fstat(4, {st_mode=S_IFREG|0640, st_size=7998, ...}) = 0 
lseek(4, 0, SEEK_SET) 
...
```
Because of the /usry/local build neomutt was **not** trying to open the UNIX-default /etc/mime.types but searching for it in `~/.mimetypes`,` /usr/local/etc/mimetypes` and ` /usr/local/share/mutt/mime.types`.
in contrast, the strace of the working debian built mutt with SYSCONFDIR set to /etc:

```
...
rt_sigaction(SIGINT, {sa_handler=0x557290aa3fe0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fc8e3d9d030}, NULL, 8) = 0 
open("/home/chris/.mime.types", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/etc/mime.types", O_RDONLY)       = 4    
fstat(4, {st_mode=S_IFREG|0644, st_size=24301, ...}) = 0 
...
```
# WORKAROUNDS

## Compile with corrected SYSCONFDIR

rebuild your source with:

`./configure --sysconfdir=/etc
`
OR
`./prepare --sysconfdir=/etc
`
then `make` as usual.

## Create symbolic links

Either in your $HOME:

`ln -s /etc/mime.types ~./.mime.types

Or "systemwide" (as root):
`sudo ln -s /etc/mime.types /usr/local/etc/mime.types`


# PROPOSED SOLUTION

1) Add `error_message()`-call for debuglog if no mime.types-file is found, as in: 4bc6051613ccf7fcf4d452b6a9b15f2a4bc55d7e

2) Add `/etc/mime.types` to files-loop in `mutt_lookup_mime_types()` (sendlib.c:951) as in: 3cf7de675f071ec26964e7f60441727cb97a05a2

add) as `man hier` states:

       /usr/local/etc
              Configuration files associated with locally installed programs.

      /etc   
              Contains configuration files which are local to the machine.

 the mime.types file is not directly associated with mutt, so I think we should honor the Unix-Default (see:  [Wikipedia](https://en.wikipedia.org/wiki/Media_type#mime.types))

# FEEDBACK

@toogley: Could you please check if my implementation in `sendlib.c:951 mutt_lookup_mime_types()` makes sense? I figured this code goes through all files in the "for-case-statement" an returns the last match, therefore I added /etc/mime.types on position 0 to not interfere with existing setups, that might be different. As it is getting late, I am not sure if my concentration is at its best - thanks! ;-)

@flatcap: May I bother you to - pending toogley's and your approval and testing - to merge this branch (devel/issue-556) with master? I am currently not up2date with neomutts coding standards - sorry. :-(

@sassmann: Did you compile neomutt from source yourself or are using a package? May I ask you to try out a workaround that fits you and give me feedback if it remedied your problem?

**Comment by toogley** [comment] 2017-06-17 08:21
@christopher-john-czettel i'm not experienced enough to make a good review.

**Comment by christopher-john-czettel** [comment] 2017-06-17 13:05
@toogley thanks for the info. Next time I'll ask the reviewers team. Is anything left to do, or will this patch enter master/release whenever it's time automatically?

**Comment by toogley** [comment] 2017-06-17 13:17
@christopher-john-czettel i guess it'll be merged if @flatcap finds the time to look at it.

**Comment by toogley** [comment] 2017-06-17 13:20
@christopher-john-czettel however, you should of course fix my and @ghar 's notes.^^

**Comment by sassmann** [comment] 2017-06-18 15:04
Hi @christopher-john-czettel,
thanks for looking into this. I've built your branch locally.
Looking at strace I see that /etc/mime.types is now being opened.
```
7199  open("/etc/mime.types", O_RDONLY) = 5
7199  open("/etc/mutt/mime.types", O_RDONLY) = -1 ENOENT (No such file or directory)
7199  open("/usr/share/mutt/mime.types", O_RDONLY) = -1 ENOENT (No such file or directory)
7199  open("/home/sassmann/.mime.types", O_RDONLY) = 5
```

I've noticed that in mutt when I've attached the file it is now recognized
`A     2 /dev/shm/test.odt   [applica/vnd.oasis., base64, 34K]
`
Now I'm able to add a mailcap entry to properly handle this. Solves my problem. 👍

**Comment by christopher-john-czettel** [comment] 2017-06-18 15:31
your welcome @sassmann. PR #637 will integrate this.

**Closed by christopher-john-czettel** 2017-06-18 15:31 UTC
Labels: bug:confirmed, has:patch, type:bug
