### ISSUE TITLE
sidebar-next-new no longer reacts to unread mail

### ISSUE THREAD

**Issue by emtiu** [neomutt/neomutt#2681] opened 2020-10-02 11:59 UTC
Until 2020-08-21, the `sidebar-next-new` and `sidebar-prev-new` bindings would cause the sidebar highlight to move to the next/previous mailbox with _**either new or unread**_ messages, and I (and I suspect many others) have come to expect this behavior.

However, since 2020-09-25, the `sidebar-next-new` and `sidebar-prev-new` bindings act **_exclusively on mailboxes with new mail_**.

This leaves users without a way to jump straight to mailboxes with _unread_ mail. With a large number of mailboxes, this is a big inconvenience.

If `sidebar-next/prev-new` are meant to behave like this, there should at least be additional **`sidebar-next/prev-unread`** bindings to behave like `sidebar-next/prev-new` did before. Otherwise, users will be left to arduously single-step across any number of mailboxes to reach the next with unread messages.

**Comment by brunnre8** [comment] 2020-10-04 14:24
fixed via 6078653c9233644ca76c24bdb64e49bd443dd714

**Comment by gahr** [comment] 2020-10-04 15:02
Duplicate of #2670.

**Closed by gahr** 2020-10-04 15:02 UTC
Labels: type:bug
