### ISSUE TITLE
mutt html attachments don't persist

### ISSUE THREAD

**Issue by wgmayer0** [neomutt/neomutt#3219] opened 2022-01-26 19:46 UTC
When I open an attachment in mutt, the attachment opens fine.

Here is my mailcap file:
```
text/html; ( nohup qutebrowser %s > /dev/null 2>&1 & ); nametemplate=%s.html;
text/plain; nohup less %s > /dev/null 2>&1 &
image; ( nohup feh %s > /dev/null 2>&1 & )
audio/video; ( nohup mpv %s > /dev/null 2>&1 & )
application/pdf; ( nohup zathura %s > /dev/null 2>&1 & )
application/octet-stream; ( nohup zathura %s > /dev/null 2>&1 & )
```

When I close mutt, qutebrowser turns completely blank. This behavior is not consistent. *Sometimes* qutebrowser will *not* turn blank. But more times than not it does.

Here is a before and after screenshot:
![before](https://user-images.githubusercontent.com/73801421/151235573-128060e2-d5a7-4b65-bdb0-7f1e96c2e334.png)
![after](https://user-images.githubusercontent.com/73801421/151235591-dcbac579-0ebd-46fa-aaec-c57a43897c20.png)

*Right now it is working, but as soon as I see it not work, I will post some more screenshots*

**Comment by wgmayer0** [comment] 2022-01-26 20:19
It just happened. I had 3 qutebrowser windows open and they all crashed once I closed neomutt. They just stay blank and blink. I tried opening up another qutebrowser session and it would not open. It also was blank and blinked. Same thing happens on firefox (untested because I cannot easily reproduce). What is causing these applications to crash?

**Comment by gahr** [comment] 2022-01-27 07:50
NeoMutt will remove temporary files on exit. If you want to persist them, you need to script that on your mailcap entry.

**Comment by wgmayer0** [comment] 2022-01-27 07:52
Ok what is the best way to script it?

**Comment by wgmayer0** [comment] 2022-01-27 08:06
Also this does not explain why sometimes it stays and other times it crashes into a blank page.

**Comment by gahr** [comment] 2022-01-27 08:36
> Also this does not explain why sometimes it stays and other times it crashes into a blank page.

It might be that we don't always manage to delete the file, or the browser sometimes doesn't notice that it's gone or doesn't care, perhaps because you don't change focus or something. Can you please check whether the temporary file is always deleted when you quit neomutt?

> Ok what is the best way to script it?

something like this?

```
text/html; call_browser.sh %s
```

```
% cat call_browser.sh
TMP="$(mktemp)"
cp $1 "$TMP" # it's up to you to get rid of $TMP now...

qutebrowser "$TMP" > /dev/null 2>&1 &
```

**Comment by wgmayer0** [comment] 2022-01-27 15:42
Ok, thanks. I'll try it. If I put an rn $TMP after qutebrowser that should
delete it on qutebrowser close.

Only thing is I tried something similar to this before and it didn't work.
I still had all qutebrowser windows crash and turn white. But let's see if
this code works because it varies from what I used before. Thanks!

**Comment by wgmayer0** [comment] 2022-02-07 19:13
Thanks I tried this and it is opening up as a text file. See attached.
![1644261221](https://user-images.githubusercontent.com/73801421/152855918-e9c1474d-7067-4509-b2be-670f1ef0c97a.png)

**Comment by gahr** [comment] 2022-02-08 07:21
Perhaps qutebrowser expects a file with a .html extension? Try putting the `nametemplate=%s.html` part back into your mailcap entry.

**Comment by wgmayer0** [comment] 2022-02-08 08:08
Dang - that did not work

**Comment by gahr** [comment] 2022-02-08 08:17
Ah, sure, you want to have the **final** file be named something.html. You can remove the `nametemplate=%s.html` from your mailcap and change your script to generate the temporary file as `$(mktemp --tmpdir qutebrowser-XXXXX.html)` or something (assuming you're on Linux).

**Comment by wgmayer0** [comment] 2022-02-08 08:25
So that did fix it and it displays now, but the original issue is still happening. The qutebrowser window crashes when I kill neomutt.

**Comment by gahr** [comment] 2022-02-08 08:45
I don't see how killing neomutt could impact the temporary file, at this point.

**Comment by wgmayer0** [comment] 2022-02-09 05:21
Can we open this back up?

**Comment by gahr** [comment] 2022-02-09 07:20
Sure, do you have any additional information that suggests NeoMutt is interfering with the temporary file you're creating?

**Comment by dcpurton** [comment] 2022-02-09 12:55
@wgmayer0 some things you could check:

When you close Neomutt:

- is the temporary file still present, like we expect?
- does the temporary file contain what you expect it to contain?

Other thoughts:

- is there a quoting problem with the `cp` command in your wrapper script? Does `cp "$1" "$TMP"` improve things?
- what happens if you use a different browser?

**Comment by wgmayer0** [comment] 2022-02-11 00:28
When I use firefox, it crashes.

**Comment by The-Compiler** [comment] 2022-02-11 08:59
> I'm pretty sure firefox is happy to keep displaying a file after it's `rm`'d from disk.

FWIW, so is qutebrowser. I've been using qutebrowser to display HTML mails in neomutt for a long time, and so have others, without any issues.

**Comment by wgmayer0** [comment] 2022-02-12 07:20
Tonight I am using it and firefox is not crashing, but qutebrowser is crashing. Setting the script aside for a second, I am wondering what changes when neomutt is killed. Tmp files are deleted? I don't think that should cause qutebrowser to erase the file from ram because the file was read. I can understand if I switch pages and then return back to the page and it is gone because I am reloading the file and it's not there. But I am curious why qutebrowser totally crashes on *ALL* open windows, *sometimes*. Same with firefox. Sometimes it works, other times it doesn't.

script that is bound to my key that starts mutt:
```
#!/bin/bash

xterm -e neomutt &
P1=$!
mbsync -V gmail &
P2=$!
notmuch new &
P3=$!
wait $P1 $P2 $P3
```

muttrc:
```
source /home/wgm/.mutt/aliases
source /home/wgm/.mutt/keybindings/unbindkeys
source /home/wgm/.mutt/keybindings/keybindings.index
source /home/wgm/.mutt/keybindings/keybindings.attach
source /home/wgm/.mutt/keybindings/keybindings.pager

# set the mailcap file
set mailcap_path = ~/.mutt/mailcap
set implicit_autoview = yes

# stop the "press any key to continue"
set wait_key=no

# appearance
set help=off

# editor
set editor = "vim -S /home/wgm/.vimrc"

# pager
set pager=vim

# delete
set delete=yes

# turn on autotagging messages
set auto_tag=yes

# format the status bar
color status white black
set status_format=''

# disable history
set history=0

# use mbsync
set mbox_type=Maildir
set folder=~/.mutt/mail
set spoolfile="+INBOX"
unset postponed
unset record
mailboxes +INBOX

# use msmtp
set sendmail="/usr/bin/msmtp"
set realname="W. Grant Mayer"
set use_from=yes
set envelope_from=yes
set edit_headers=yes
set autoedit

# format dates
set index_format=' %<[y?%<[m?%<[d?%[%H:%M ]&%[%a %d]>&%[%b %d]>&%[%m/%y ]>  %S  %-14.14n  %s '

# set autoview up for html
auto_view text/html

# pipe decode on
set pipe_decode=yes

# auto download attachments
set attach_save_dir=/home/wgm/downloads
set attach_save_without_prompting=yes
```

mailcap:
```
text/html; ( nohup qutebrowser %s > /dev/null 2>&1 & ); nametemplate=%s.html;
text/plain; nohup less %s > /dev/null 2>&1 &
image; ( nohup feh %s > /dev/null 2>&1 & )
audio/video; ( nohup mpv %s > /dev/null 2>&1 & )
application/pdf; ( nohup zathura %s > /dev/null 2>&1 & )
application/octet-stream; ( nohup zathura %s > /dev/null 2>&1 & )
```

**Comment by wgmayer0** [comment] 2022-02-12 07:29
@The-Compiler can you provide your mailcap? Maybe `nohup` is causing the problem. I f I use `qutebrowser %s &; nametemplate=%s.html`, qutebrowser closes *with* neomutt even though it is being ran in the background...

**Comment by The-Compiler** [comment] 2022-02-12 08:20
`text/html; qutebrowser --temp-basedir -s content.proxy http://localhost:666 -s content.javascript.enabled false %s; needsterminal; nametemplate=%s.html` is what I have. To be fair I haven't tried quitting neomutt with qutebrowser open. You can ignore the `-s ...` settings, those are just to disallow internet access and JS.

**Comment by wgmayer0** [comment] 2022-02-12 15:43
Thanks!

**Comment by dcpurton** [comment] 2022-02-14 01:34
> @The-Compiler can you provide your mailcap? Maybe `nohup` is causing the problem. I f I use `qutebrowser %s &; nametemplate=%s.html`, qutebrowser closes _with_ neomutt even though it is being ran in the background...

FWIW with this mailcap entry:

```
text/html; qutebrowser '%s' &; test=test -n "$DISPLAY"; description="HTML Text"; nametemplate=%s.html
```

qutebrowser opens in the background and does not close or crash when I quite Neomutt. I can open multiple HTML attachments (use `<view-attach>` or `<view-mailcap>` and they open up in new tabs in the existing qutebrowser window.

**Comment by dcpurton** [comment] 2022-02-15 00:56
Yes! If I use `xterm -e neomutt` then qutebrowser does close when I exit Neomutt.

**Comment by wgmayer0** [comment] 2022-02-15 01:04
Ok - I am using `text/html; ( qutebrowser '%s' > /dev/null 2>&1 & ); test=test -n "$DISPLAY"; description="HTML Text"; nametemplate=%s.html` and it is working even with my startup script:

```
#!/bin/bash

xterm -e neomutt &
P1=$!
mbsync -V gmail &
P2=$!
notmuch new &
P3=$!
wait $P1 $P2 $P3
```

**Comment by wgmayer0** [comment] 2022-02-15 01:09
And now it's not working when I restarted mutt and tested it again. Doesn't make sense why it's behavior would change all else being equal. Hmm...

**Comment by dcpurton** [comment] 2022-02-15 01:19
I think you are lucky at present maybe. There is definitely something weird going on. Wihtout a `nohup` qutebrowser still closes for me.

If I use the script to make a copy of the HTML file like above and include a `nohup` to keep qutebrowser open I still get the blank white window.

The HTML file is still present and looks good, but if I try to reload it then qutebrowser gets stuck in a flickering loop.

**Comment by wgmayer0** [comment] 2022-02-15 01:30
Just curious - if you replace with `firefox` does it crash?

**Comment by wgmayer0** [comment] 2022-02-15 01:33
If I remove `; nametemplate=%s.html` then it works and stays open after closing - just everything is in html source code. `text/html; ( nohup qutebrowser %s > /dev/null 2>&1 & )`

**Comment by wgmayer0** [comment] 2022-02-15 01:33
Never mind - it doesn't. Maybe I was lucky again

**Comment by wgmayer0** [comment] 2022-02-15 01:42
Same thing happens to me on firefox. It says 'Your tab has crashed.' This happens when I use `text/html; ( nohup firefox %s > /dev/null 2>&1 & ); needsterminal; nametemplate=%s.html`

**Comment by wgmayer0** [comment] 2022-02-15 01:48
Sometimes I get this: it seems to be random
![1644889582](https://user-images.githubusercontent.com/73801421/153977242-f442c359-ebf9-47c6-aedd-d10a15bdd553.png)

**Comment by wgmayer0** [comment] 2022-02-15 01:49
However, I just tried it again and I was able to open the exact same html document... strange

**Comment by gahr** [comment] 2022-02-15 07:31
Couple of things here:
1. NeoMutt will remove its temporary files when it quits. That's why I suggested to copy NeoMutt's temporary file into a temporary file whose lifetime is controlled by the script invoked in your mailcap.
2. While I'm pretty sure that if you `nohup xterm -e cmd`, `cmd` survives your closing `xterm`, I'm not as convinced that `xterm -e nohup cmd` does the same. I think xterm might send a number of signals depending on exactly how it is configured and terminated.
3. None of this is related to NeoMutt :)

**Comment by jakubkaczor** [comment] 2022-02-22 13:12
@gahr these are valid points. I think one thing is related to both, the issue and neomutt. Creating that temporary file by copying is inefficient. Imagine having 1 GiB attachment, and having to copy it. The solution is simple. Use *hard* links. The problem is with the way neomutt removes the attachment file from `/tmp` directory. Let's say neomutt creates a file `/tmp/file` (attachment). Then, I would like to create hard link `/tmp/mail-attachments/file`. In this way, closing neomutt should remove `/tmp/file` and leave `/tmp/mail-attachments/file` untouched. Therefore, you can still access the file contents. I tested this by removing `/tmp/file` with `rm` and then closing neomutt, it worked. But if you leave removing `/tmp/file` to neomutt, it doesn't. It leaves the hard link broken.

Here is a method of handling the issue discussed that worked for me, I suggest trying it out. First, create the opening script. I will name it `neomutt-open`.
``` sh
#!/bin/sh

# $1 is the default attachment path
TMPDIR="/tmp/neomutt-mail-attachments"
attachment_basename="$(basename $1)"
new_attachment_path="$TMPDIR/$attachment_basename"

mkdir -p "$TMPDIR"
cp -f "$1" "$new_attachment_path"
setsid -f xdg-open "$new_attachment_path"
```
As you can see, I use `setsid -f` instead of `nohup`, the purpose is the same. You can replace xdg-open with other file opener. Then, edit the mailcap entry to `text/html; neomutt-open %s; nametemplate=%s.html`.

I think you should replace `cp` in the script with `ln`, but you can't because of the problem I described in the first paragraph.

**Comment by mschilli87** [comment] 2022-02-22 13:35
@jakubkaczor:
> But if you leave removing /tmp/file to neomutt, it doesn't. It leaves the hard link broken.

If that's the root cause you might want to change the title of this issue and investigate further.
While I would say that attachmens not persisting when closing `neomutt` is the intended behaviuor, I would consider breaking an independently created hard link to that file a bug.
Maybe you can find out what exactly `neomutt` is doing (wrong) when deleting the attachments and potentially even suggest a fix via a PR? Seems more productive to me than discussing about specific browsers, whether attachments should persists, and how to exactly script around the problem for that particular use case. :wink:

**Comment by gahr** [comment] 2022-02-22 13:48
Good catch - we are indeed doing something fishy when we remove the tmp file:
https://github.com/neomutt/neomutt/blob/2ccae1a89d87302c3bef634ab5196a18135f9241/mutt/file.c#L220-L230

**Comment by gahr** [comment] 2022-02-22 13:53
So I think we want to make sure we really really get rid of the file contents, for privacy/security purposes. Don't ask me.. copying the file *is* the workaround. You can even move the file I guess.

**Comment by jakubkaczor** [comment] 2022-02-22 13:54
@mschilli87 I somewhat agree. Unfortunately, I don't have any knowledge about the programming language C and neomutt codebase, so for now I won't be productive in investigating into code or programming the solution. The discussion about scripting out not persisting attachments has grown. Perhaps, opening another issue about removing temporary files would be a better idea, unless, the problem is easy to solve and demands little to no discussion. What do you think?

**Comment by jakubkaczor** [comment] 2022-02-22 14:02
@gahr I considered moving the file, but then, opening a file mulitple times using neomutt and mailcap would create multiple writes and moves. It is definitely better than copying, but I think hard link would be the best fit.

When it comes to privacy, I assume the purpose of deleting the file contents is, so the data cannot be read from the disk anymore. I don't know how this creation of attachment file by neomutt is done, but isn't the attachment available in the readable form, somewhere in the mail folder, anyway? Unless, you are reading directly from something like IMAP.

**Comment by mschilli87** [comment] 2022-02-22 14:03
@gahr:
Thank you for looking into this so quickly.

> So I think we want to make sure we really really get rid of the file contents, for privacy/security purposes.

Sounds like a legit reason to me, but this should probably be better documents and maybe even configurable(?).

---
@jakubkaczor:
No problem, that's why I wrote 'maybe'. ;-)
AFACT, thx to @gahr you know have your answer: `neomutt` not only deletes but also zeroes out the content of the file to prevent uninteded leakage of the attachment's potentiall sensitive content.
If that's was a good decision or not would be a question for another issue if you asked me.
But unlesss you can work on it, I doubt there is going to be much interest/capacity to work on this right now.
So to me it looks like you'll have to live with copying for now but at least now you know *why*. :wink:

**Comment by gahr** [comment] 2022-02-22 14:59
If it was me, I'd just unlink the file and remove the "fill it with zeros" part. If you want strong security guarantees including wiping out disk sectors and everything, you can do it on the filesystem level / with an external tool. @flatcap what's your take?

**Comment by flatcap** [comment] 2022-02-22 16:04
That code dates back to Mutt's initial commit (24 years ago), but the idea seems a bit off, these days.

We've had a bit of discussion on IRC and we're agreed that we can't outwit the OS and filesystem.
If we write the plain-text file to disk, we can't be certain that the data hasn't been duplicated.
When we write the zeroes to disk, a modern filesystem and/or SSD might not overwrite the original data.

Add to that, that many users have full-disk encryption and have their `/tmp` in RAM.

I'm in favour of killing the zeros, too -- just unlink the file.

---

You can also find us on IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))

**Comment by wgmayer0** [comment] 2022-02-22 16:40
> @gahr these are valid points. I think one thing is related to both, the issue and neomutt. Creating that temporary file by copying is inefficient. Imagine having 1 GiB attachment, and having to copy it. The solution is simple. Use _hard_ links. The problem is with the way neomutt removes the attachment file from `/tmp` directory. Let's say neomutt creates a file `/tmp/file` (attachment). Then, I would like to create hard link `/tmp/mail-attachments/file`. In this way, closing neomutt should remove `/tmp/file` and leave `/tmp/mail-attachments/file` untouched. Therefore, you can still access the file contents. I tested this by removing `/tmp/file` with `rm` and then closing neomutt, it worked. But if you leave removing `/tmp/file` to neomutt, it doesn't. It leaves the hard link broken.
> 
> Here is a method of handling the issue discussed that worked for me, I suggest trying it out. First, create the opening script. I will name it `neomutt-open`.
> 
> ```shell
> #!/bin/sh
> 
> # $1 is the default attachment path
> TMPDIR="/tmp/neomutt-mail-attachments"
> attachment_basename="$(basename $1)"
> new_attachment_path="$TMPDIR/$attachment_basename"
> 
> mkdir -p "$TMPDIR"
> cp -f "$1" "$new_attachment_path"
> setsid -f xdg-open "$new_attachment_path"
> ```
> 
> As you can see, I use `setsid -f` instead of `nohup`, the purpose is the same. You can replace xdg-open with other file opener. Then, edit the mailcap entry to `text/html; neomutt-open %s; nametemplate=%s.html`.
> 
> I think you should replace `cp` in the script with `ln`, but you can't because of the problem I described in the first paragraph.

This is a great solution - but there is something important to note. Without doing anything concerning `TMP` files, I am able to get it working by replacing the `nohup` in my original code with `setsid -f`. So it goes from:
```
text/html; ( nohup -f qutebrowser %s > /dev/null 2>&1 & ); needsterminal; nametemplate=%s.html
```
and becomes:
```
text/html; ( setsid -f qutebrowser %s > /dev/null 2>&1 & ); needsterminal; nametemplate=%s.html
```

Works perfectly... Unless I am "lucky" right now. Lol.

**Comment by jakubkaczor** [comment] 2022-02-22 16:56
@wgmayer0 I'm glad I could help. 😉

**Comment by flatcap** [comment] 2022-02-23 10:16
@wgmayer0 
Thanks for pushing us to investigate this.
Sorry it took a month's discussion to find out what was going wrong.

**Comment by wgmayer0** [comment] 2022-02-23 13:39
Yes thanks for getting to the bottom of it! I appreciate it!

**Closed** 2022-03-01 14:03 UTC
Labels: type:question
