### ISSUE TITLE
Warning on use for ".i" macro - 1.8.3-20170602

### ISSUE THREAD

**Issue by sadsfae** [neomutt/neomutt#621] opened 2017-06-07 12:57 UTC
Hey Folks,

After upgrading from ```1.8.2-20170421``` to ```1.8.3-20170602``` I'm getting non-fatal warnings opening mutt.

Here is the warning:

```
Warning: For menu 'index', binding '.i' will alias '.'
Warning in /home/wfoster/.muttrc-local, line 7: 
source: 1 warnings in /home/wfoster/.muttrc-local
Press any key to continue...
```

Here is my corresponding configuration line:

```
macro index .i  "<limit>(~N|~F)<Enter>"  "view new/flag"
```

Are there some configuration syntax changes I should be switching to?  I couldn't find anything about it and I've been using this macro for years.  A way to disable warnings like this would be sufficient too.  I thought I'd report this in case anyone else hits it after upgrading with macros prefixed with ```.```

**Comment by toogley** [comment] 2017-06-07 13:13
can you try to put this before your macro definiton?

    macro index . noop

**Comment by somini** [comment] 2017-06-07 13:39
References #451 
Duplicate of #583

**Comment by sadsfae** [comment] 2017-06-07 13:56
> can you try to put this before your macro definiton?

```macro index . noop```

Hey @toogley I've placed this prior to the index line but it also incurs a warning.

```
Warning: For menu 'index', binding '.i' will alias '.'
Warning in /home/wfoster/.muttrc-local, line 10: 
source: 1 warnings in /home/wfoster/.muttrc-local
Press any key to continue...
```

**Comment by flatcap** [comment] 2017-06-07 14:17
As `.` is a default **binding**, try:
```
bind index . noop
```

**Comment by flatcap** [comment] 2017-06-07 14:34
@somini 
Whether the user is `bind`-ing or `macro`-ing the solution is to `bind` to `noop`.
So, I've made a slight tweak to the error messages to suggest what to do:
```
Suggestion: bind index g noop
```

The wording needs to be better and it should explain where to put the config.
Improvements welcomed.

**Comment by somini** [comment] 2017-06-07 14:46
@flatcap Good idea. We can always write a paragraph on the manual and link users there.

**Comment by sadsfae** [comment] 2017-06-07 14:55
@flatcap binding ```.``` as noop first works for me.

```
bind index . noop
macro index .i  "<limit>(~N|~F)<Enter>"  "view new/flag"
```

**Closed** 2017-06-07 14:56 UTC
Labels: type:question

**Comment by flatcap** [comment] 2017-06-07 15:46
I've had to tweak the messages slightly.

The three line: "warning; webpage; suggestion" looked good on startup, but got mangled if it was displayed whilst mutt was running.  I've reordered and trimmed it a bit to be useful on a 80 char screen
```
Binding 'xx' will alias 'x'  Before, try: 'bind pager x noop'  https://neomutt.org/guide/configuration.html#bind-warnings
```

The docs are now live: https://www.neomutt.org/guide/configuration.html#bind-warnings
