### ISSUE TITLE
Add += and -= to the config system

### ISSUE THREAD

**Issue by jindraj** [neomutt/neomutt#2236] opened 2020-04-04 13:12 UTC
### From IRC #neomutt - flatcaps thoughts about the feature:
I'd like to add += and -= to the config system, but I'd need a volunteer
(I have an idea how it'd work, but I haven't investigated it fully)
most of it would be trivial :-)

the tricky bit would be altering parse_set()
that function's been overhauled since the mutt days, so it's not too scary

I just haven't looked at what would be involved
a simple version would add some functions to ConfigSetType: plus_equals(), minus_equals()

(initially) we'd only implement those functions for numeric types: config/number,long
then in parse_set(), there's a `if (*s->dptr == '=')` which is looking for 'set x = y'
we'd want extra bits in there testing for `+=` and `-=`

the job of parse_set() is to split up the string and decide which function to call
the job of setting, resetting, adding, etc is done by the dedicated config types

## What would you like to be able to do?
Increment and decrement numeric config values.

Executing
- `set variable += N` would take current value of the variable and increment it by **N**
- `set variable -= N` would take current value of the variable and decrement it by **N**

## What needs to change in NeoMutt?
Described in the header text.

## Have you tried any alternative methods?
Yes
- Macros
Would be probably possible but would be messy.
- Lua
Works nice:
```
lua mutt.set("variable",mutt.get("variable") + 1)
lua mutt.set("variable",mutt.get("variable") - 1)
```

**Comment by hsanson** [comment] 2020-04-06 11:58
This is duplicate of #243

**Closed** 2020-04-15 20:15 UTC
Labels: closed:duplicate
